-- Historical Quality Control import for C2026 supplemental audit.
-- Idempotent and non-destructive: existing boat, area and defect records are not overwritten.
begin;
insert into public.quality_control_boats (id,name,model) values ('qc-reference-c2026','C2026','C2') on conflict (id) do nothing;
insert into public.quality_control_areas (boat_id,area_name,sort_order) values ('qc-reference-c2026','Saloon',0) on conflict (boat_id,area_name) do nothing;
insert into public.quality_control_areas (boat_id,area_name,sort_order) values ('qc-reference-c2026','Aft Cockpit',1) on conflict (boat_id,area_name) do nothing;
insert into public.quality_control_areas (boat_id,area_name,sort_order) values ('qc-reference-c2026','Stbd Engine Room',2) on conflict (boat_id,area_name) do nothing;
insert into public.quality_control_areas (boat_id,area_name,sort_order) values ('qc-reference-c2026','Port Engine Room',3) on conflict (boat_id,area_name) do nothing;
insert into public.quality_control_areas (boat_id,area_name,sort_order) values ('qc-reference-c2026','Stbd Fwd Heads',4) on conflict (boat_id,area_name) do nothing;
insert into public.quality_control_areas (boat_id,area_name,sort_order) values ('qc-reference-c2026','Stbd Fwd Cabin',5) on conflict (boat_id,area_name) do nothing;
insert into public.quality_control_areas (boat_id,area_name,sort_order) values ('qc-reference-c2026','Stbd Passage',6) on conflict (boat_id,area_name) do nothing;
insert into public.quality_control_areas (boat_id,area_name,sort_order) values ('qc-reference-c2026','Owner''S Heads',7) on conflict (boat_id,area_name) do nothing;
insert into public.quality_control_areas (boat_id,area_name,sort_order) values ('qc-reference-c2026','Study',8) on conflict (boat_id,area_name) do nothing;
insert into public.quality_control_areas (boat_id,area_name,sort_order) values ('qc-reference-c2026','Stbd Aft Cabin',9) on conflict (boat_id,area_name) do nothing;
insert into public.quality_control_areas (boat_id,area_name,sort_order) values ('qc-reference-c2026','Port Aft Cabin',10) on conflict (boat_id,area_name) do nothing;
insert into public.quality_control_areas (boat_id,area_name,sort_order) values ('qc-reference-c2026','Port Aft Heads',11) on conflict (boat_id,area_name) do nothing;
insert into public.quality_control_areas (boat_id,area_name,sort_order) values ('qc-reference-c2026','Port Side Deck',12) on conflict (boat_id,area_name) do nothing;
insert into public.quality_control_areas (boat_id,area_name,sort_order) values ('qc-reference-c2026','Stbd Side Deck',13) on conflict (boat_id,area_name) do nothing;
insert into public.quality_control_areas (boat_id,area_name,sort_order) values ('qc-reference-c2026','Stbd Hull',14) on conflict (boat_id,area_name) do nothing;
insert into public.quality_control_areas (boat_id,area_name,sort_order) values ('qc-reference-c2026','Forepeak',15) on conflict (boat_id,area_name) do nothing;
insert into public.quality_control_areas (boat_id,area_name,sort_order) values ('qc-reference-c2026','Port Fwd Cabin',16) on conflict (boat_id,area_name) do nothing;
insert into public.quality_control_areas (boat_id,area_name,sort_order) values ('qc-reference-c2026','Port Fwd Heads',17) on conflict (boat_id,area_name) do nothing;
insert into public.quality_control_areas (boat_id,area_name,sort_order) values ('qc-reference-c2026','Port Passage',18) on conflict (boat_id,area_name) do nothing;
insert into public.quality_control_areas (boat_id,area_name,sort_order) values ('qc-reference-c2026','Port Mid Cabin',19) on conflict (boat_id,area_name) do nothing;
insert into public.quality_control_areas (boat_id,area_name,sort_order) values ('qc-reference-c2026','Port Mid Heads',20) on conflict (boat_id,area_name) do nothing;
insert into public.quality_control_areas (boat_id,area_name,sort_order) values ('qc-reference-c2026','Flybridge',21) on conflict (boat_id,area_name) do nothing;
insert into public.quality_control_areas (boat_id,area_name,sort_order) values ('qc-reference-c2026','Fwd Cockpit & Foredeck',22) on conflict (boat_id,area_name) do nothing;
insert into public.quality_control_defects (id,boat_id,area_name,item,failure_mode,description,code,discipline,concern,repaired_by,repaired_date,team_leader_check,qc_rwk,qc_acc) values
  ('qc-source-c2026-qc3-r4','qc-reference-c2026','Saloon','Companion door','Damage','Spills and damages on companionway door frame check entire frame',9,'Spray Painting',false,'','','','',''),
  ('qc-source-c2026-qc3-r5','qc-reference-c2026','Saloon','Companion door','Missing part','Missing bolt covers bottom and top',4,'Deckfitting',false,'','','','',''),
  ('qc-source-c2026-qc3-r6','qc-reference-c2026','Saloon','Companion door','Loose','Loose catch block - port outer side',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r7','qc-reference-c2026','Saloon','Companion door','Missing part','Missing cover strip on companionway door frame bottom area',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r8','qc-reference-c2026','Saloon','Locker lids','Damage','Damaged floor lifter rubbers - check all',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r9','qc-reference-c2026','Saloon','Locker lids','Damage','Damages on aft battery locker lid',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r10','qc-reference-c2026','Saloon','Locker lids','Damage','Damages on fwd battery locker lid',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r11','qc-reference-c2026','Saloon','Locker lids','Missing part','Missing floor studs on aft locker lid',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r12','qc-reference-c2026','Saloon','Floor','Sealer','Floor sealer stepping - check all floor sealer as marked',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r13','qc-reference-c2026','Saloon','Aircon unit','Repairs','Aircon inspection - remove peel ply and loose fibre glass strands',1,'Gelcoat',false,'','','','',''),
  ('qc-source-c2026-qc3-r14','qc-reference-c2026','Saloon','Windows','Cleaning','Clean all mullion covers and windows',10,'Cleaning',false,'','','','',''),
  ('qc-source-c2026-qc3-r15','qc-reference-c2026','Saloon','Aircon unit','Cleaning','Aircon vent aft of galley is dirty - clean, check entire',10,'Cleaning',false,'','','','',''),
  ('qc-source-c2026-qc3-r16','qc-reference-c2026','Saloon','Magazine locker/shelf locker','Cleaning','Clean port shelf between GRP liner and shelf',10,'Cleaning',false,'','','','',''),
  ('qc-source-c2026-qc3-r17','qc-reference-c2026','Saloon','window surround','Scratches','Scratches and dull on port GRP liner',1,'Gelcoat',false,'','','','',''),
  ('qc-source-c2026-qc3-r18','qc-reference-c2026','Saloon','window surround','Scratches','Scratches and dull on starboard GRP liner',1,'Gelcoat',false,'','','','',''),
  ('qc-source-c2026-qc3-r19','qc-reference-c2026','Saloon','Window blinds','Operational','Twisted port fwd blind strings - port aft blind string',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r20','qc-reference-c2026','Saloon','Window','Damage','Damages on primer on port aft window',4,'Deckfitting',false,'','','','',''),
  ('qc-source-c2026-qc3-r21','qc-reference-c2026','Saloon','Window blinds','Cleaning','Clean all blinds as marked',10,'Cleaning',false,'','','','',''),
  ('qc-source-c2026-qc3-r22','qc-reference-c2026','Saloon','Fwd cockpit door','Operational','Forward cockpit blind strings loose and twisted',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r23','qc-reference-c2026','Saloon','Fwd area','Sealer','Neaten sealer fwd of sink',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r24','qc-reference-c2026','Saloon','Corian','Loose','Loose corian sleeve',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r25','qc-reference-c2026','Saloon','Companion door','Operational','Adjust companion way door and check alignment',4,'Deckfitting',false,'','','','',''),
  ('qc-source-c2026-qc3-r33','qc-reference-c2026','Saloon','Window blinds','Proud/Alignment','Port centre blind not covering entire window, light coming through',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r34','qc-reference-c2026','Saloon','Window blinds','Proud/Alignment','Starboard centre blind not covering entire window, light coming through',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r35','qc-reference-c2026','Saloon','Oven','Operational','Electric oven shaving on bottom pot drawer',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r36','qc-reference-c2026','Saloon','Galley lockers','Operational','Galley locker drawers open when locked - as marked',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r37','qc-reference-c2026','Saloon','Fridge','Proud/Alignment','Two drawer fridge not aligned',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r38','qc-reference-c2026','Saloon','Fridge','Proud/Alignment','Fridge aft of sink stepping',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r39','qc-reference-c2026','Saloon','Lockers','Loose','Loose hinges on locker below sink - check all as marked',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r40','qc-reference-c2026','Saloon','Lockers','Proud/Alignment','Bin locker door stepping',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r41','qc-reference-c2026','Saloon','Lockers','Loose','Locker aft of bin locker - fit catch and loose hinges, check all as marked',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r42','qc-reference-c2026','Saloon','Fwd cockpit door','Loose','Loose door handles x3 and knocking',4,'Deckfitting',false,'','','','',''),
  ('qc-source-c2026-qc3-r43','qc-reference-c2026','Saloon','Fwd cockpit door','Operational','Cannot semi lock',4,'Deckfitting',false,'','','','',''),
  ('qc-source-c2026-qc3-r44','qc-reference-c2026','Saloon','Lockers','Proud/Alignment','Align locker doors aft of forward cockpit door',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r45','qc-reference-c2026','Saloon','Lockers','Loose','Loose hinges and catch on all locker doors aft of forward cockpit door - as marked',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r46','qc-reference-c2026','Saloon','Lockers','Incorrect','Fire extinguisher fitted at incorrect position',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r63','qc-reference-c2026','Aft Cockpit','Lockers','Damage','Poor repair on chubby locker door above catch',4,'Deckfitting',false,'','','','',''),
  ('qc-source-c2026-qc3-r64','qc-reference-c2026','Aft Cockpit','Fridge/Freezer locker','Sealer','Smears, stains and rust marks on fridge frames - neaten sealer',4,'Deckfitting',false,'','','','',''),
  ('qc-source-c2026-qc3-r65','qc-reference-c2026','Aft Cockpit','Fwd area','Loose','Wobbly, sump lid',4,'Deckfitting',false,'','','','',''),
  ('qc-source-c2026-qc3-r66','qc-reference-c2026','Aft Cockpit','Floor','Track repair','Porosity, poor repair and pin holes on floor tracking forward of gas locker',1,'Gelcoat',true,'','','','',''),
  ('qc-source-c2026-qc3-r67','qc-reference-c2026','Aft Cockpit','Locker lids','Operational','Adjust gas locker Perco',4,'Deckfitting',false,'','','','',''),
  ('qc-source-c2026-qc3-r68','qc-reference-c2026','Aft Cockpit','Settee','Cracks','Crack at starboard galley corner below barbecue locker inboard',1,'Gelcoat',false,'','','','',''),
  ('qc-source-c2026-qc3-r69','qc-reference-c2026','Aft Cockpit','Settee','Cracks','Crack below barbecue locker outboard',1,'Gelcoat',false,'','','','',''),
  ('qc-source-c2026-qc3-r70','qc-reference-c2026','Aft Cockpit','Bbq locker','Proud/Alignment','Barbecue locker lid poorly scribed and uneven gaps',4,'Deckfitting',false,'','','','',''),
  ('qc-source-c2026-qc3-r71','qc-reference-c2026','Aft Cockpit','Bbq locker','Proud/Alignment','Barbecue locker lid hinge outboard hinge standing proud',4,'Deckfitting',false,'','','','',''),
  ('qc-source-c2026-qc3-r72','qc-reference-c2026','Aft Cockpit','Aft area','Repairs','Thin gel coat and chip off area above bridge deck flange',1,'Gelcoat',false,'','','','',''),
  ('qc-source-c2026-qc3-r73','qc-reference-c2026','Aft Cockpit','Aft area','Proud/Alignment','Port aft inspection locker lid creeking and stepping',4,'Deckfitting',false,'','','','',''),
  ('qc-source-c2026-qc3-r74','qc-reference-c2026','Aft Cockpit','Life raft locker with convertible fore/aft seat bolster','Loose','Loose grommet fitting inside life raft locker',4,'Deckfitting',false,'','','','',''),
  ('qc-source-c2026-qc3-r75','qc-reference-c2026','Aft Cockpit','Life raft locker with convertible fore/aft seat bolster','Operational','Tafflon blocks not touching swim ladder in closed position and adjust swim ladder',4,'Deckfitting',false,'','','','',''),
  ('qc-source-c2026-qc3-r77','qc-reference-c2026','Aft Cockpit','Vinyl ceiling','Damage','Broken popper at port 3rd ceiling panel',4,'Deckfitting',false,'','','','',''),
  ('qc-source-c2026-qc3-r78','qc-reference-c2026','Aft Cockpit','Vinyl ceiling','Loose','Flimsy ceiling panel starboard side as marked',4,'Deckfitting',false,'','','','',''),
  ('qc-source-c2026-qc3-r79','qc-reference-c2026','Aft Cockpit','Backrest s/s railing','Loose','Skewly fitted backrest clips starboard side and check all clips for loose',4,'Deckfitting',false,'','','','',''),
  ('qc-source-c2026-qc3-r90','qc-reference-c2026','Stbd Engine Room','Floating step','Cracks','Crack on floating step tracking',1,'Gelcoat',true,'','','','',''),
  ('qc-source-c2026-qc3-r91','qc-reference-c2026','Stbd Engine Room','Engine Room','Spills','Flow coat spills on wires and engine room surround - check entire surround as marked',1,'Gelcoat',false,'','','','',''),
  ('qc-source-c2026-qc3-r92','qc-reference-c2026','Stbd Engine Room','Engine Room','Flowcoat','Flow coat entire engine room as marked',1,'Gelcoat',false,'','','','',''),
  ('qc-source-c2026-qc3-r93','qc-reference-c2026','Stbd Engine Room','Locker lids','Loose','Loose gasket on engine room locker lid',4,'Deckfitting',false,'','','','',''),
  ('qc-source-c2026-qc3-r104','qc-reference-c2026','Port Engine Room','Engine Room','Spills','Remove spills on all marked items and GRP rooms surround',1,'Gelcoat',false,'','','','',''),
  ('qc-source-c2026-qc3-r105','qc-reference-c2026','Port Engine Room','Engine Room','Flowcoat','Remove flowcoat and neaten flowcoat as marked',1,'Gelcoat',false,'','','','',''),
  ('qc-source-c2026-qc3-r106','qc-reference-c2026','Port Engine Room','Floating step','Cracks','Crack on step in tracking',1,'Gelcoat',false,'','','','',''),
  ('qc-source-c2026-qc3-r123','qc-reference-c2026','Stbd Fwd Heads','Sliding or hinged heads door','Missing part','Fit catch and check operation of sliding door',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r124','qc-reference-c2026','Stbd Fwd Heads','Sliding or hinged heads door','Missing part','Fit silver screw cap on door lock',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r125','qc-reference-c2026','Stbd Fwd Heads','Formica Bulkheads','Sealer','Incomplete sealer behind sliding door',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r126','qc-reference-c2026','Stbd Fwd Heads','Waste tank','Damage','Visible hole in formica inside forward of waste tank locker',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r127','qc-reference-c2026','Stbd Fwd Heads','Electric sea water flush toilet','Incorrect','Incorrect screws on toilet flush switch',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r128','qc-reference-c2026','Stbd Fwd Heads','window surround','Scratches','Scratches and dull on PVC window surround',1,'Gelcoat',false,'','','','',''),
  ('qc-source-c2026-qc3-r129','qc-reference-c2026','Stbd Fwd Heads','Portlight with roller blind','Operational','Adjust roller blind to blind track',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r130','qc-reference-c2026','Stbd Fwd Heads','Under-basin locker with toilet roll holder','Loose','Loose hinges on under basin and locker',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r131','qc-reference-c2026','Stbd Fwd Heads','Formica Bulkheads','Sealer','Neaten sealer as marked',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r132','qc-reference-c2026','Stbd Fwd Heads','Hatch','Proud/Alignment','Hatch joint liner to short',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r136','qc-reference-c2026','Stbd Fwd Cabin','Door frames','Damage','Poor spray work on entire capping',9,'Spray Painting',false,'','','','',''),
  ('qc-source-c2026-qc3-r137','qc-reference-c2026','Stbd Fwd Cabin','Door frames','Sealer','Seal capping above entrance',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r138','qc-reference-c2026','Stbd Fwd Cabin','Doors','Missing part','Fit striker plate and check operation of door',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r139','qc-reference-c2026','Stbd Fwd Cabin','Hanging locker','Proud/Alignment','Hanging locker front proud',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r140','qc-reference-c2026','Stbd Fwd Cabin','Formica Bulkheads','Damage','Neaten outboard bulkhead joints',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r141','qc-reference-c2026','Stbd Fwd Cabin','Formica Bulkheads','Damage','Poor edging at top of outboard bulkhead',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r142','qc-reference-c2026','Stbd Fwd Cabin','Coat hook','Proud/Alignment','Coat hook fitted skew',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r143','qc-reference-c2026','Stbd Fwd Cabin','Fan','Incorrect','Rubber incorrect on fan',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r144','qc-reference-c2026','Stbd Fwd Cabin','Window blinds','Proud/Alignment','Twisted blind strings',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r145','qc-reference-c2026','Stbd Fwd Cabin','Light switch','Proud/Alignment','Light switches fitted skew',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r146','qc-reference-c2026','Stbd Fwd Cabin','USB outlets in each cabin','Proud/Alignment','Outlets fitted skew',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r147','qc-reference-c2026','Stbd Fwd Cabin','Floor','Sealer','Neaten floor sealer',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r148','qc-reference-c2026','Stbd Fwd Cabin','Inspection lids','Damage','Damage on inspection at forward floating step',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r149','qc-reference-c2026','Stbd Fwd Cabin','Formica Bulkheads','Damage','Visible hole at CO2 alarm',3,'Joinery/Carp',true,'','','','',''),
  ('qc-source-c2026-qc3-r162','qc-reference-c2026','Stbd Passage','Staircase','Damage','Starboard forward passage: Deep scratches on all stainless steel cappings',1,'Gelcoat',false,'','','','',''),
  ('qc-source-c2026-qc3-r163','qc-reference-c2026','Stbd Passage','Formica Bulkheads','Damage','Neaten outboard formica joints',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r164','qc-reference-c2026','Stbd Passage','Floor','Sealer','Neaten floor sealer',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r165','qc-reference-c2026','Stbd Passage','Formica Bulkheads','Damage','Neaten edging at aft bulkhead',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r192','qc-reference-c2026','Owner''S Heads','Sliding or hinged heads door','Missing part','Fit catch and check operation of sliding door',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r193','qc-reference-c2026','Owner''S Heads','Sliding or hinged heads door','Incorrect','Sliding door brackets fitted incorrect',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r194','qc-reference-c2026','Owner''S Heads','Sliding or hinged heads door','Damage','Screw protruding at top of pelmet',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r195','qc-reference-c2026','Owner''S Heads','Dividers','Missing part','Missing screw + loose divider',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r196','qc-reference-c2026','Owner''S Heads','Vanity locker with mirror','Proud/Alignment','Adjust gap on stepping vanity locker front',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r197','qc-reference-c2026','Owner''S Heads','Under-basin locker with toilet roll holder','Operational','Under basin and drawers: Adjust catches',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r198','qc-reference-c2026','Owner''S Heads','Under-basin locker with toilet roll holder','Loose','Loose toilet roll holder',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r199','qc-reference-c2026','Owner''S Heads','Hatch','Missing part','Missing screw cap on off deck catch',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r200','qc-reference-c2026','Owner''S Heads','Floor','Sealer','Neaten floor sealer',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r201','qc-reference-c2026','Owner''S Heads','Ceiling','Scratches','Scratches on ceiling',1,'Gelcoat',false,'','','','',''),
  ('qc-source-c2026-qc3-r202','qc-reference-c2026','Owner''S Heads','Portlight with roller blind','Proud/Alignment','Line up blind track on roller blind',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r203','qc-reference-c2026','Owner''S Heads','Inspection lids','Operational','Wobbly sump lid',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r226','qc-reference-c2026','Study','Staircase','Damage','Scratches on all stainless steel cappings',1,'Gelcoat',false,'','','','',''),
  ('qc-source-c2026-qc3-r227','qc-reference-c2026','Study','Vinyl ceiling','Damage','Broken ceiling poppers. Check all',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r228','qc-reference-c2026','Study','Hatch','Proud/Alignment','Deck hatch: Proud at screws',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r229','qc-reference-c2026','Study','Hanging locker','Operational','Adjust catches on hanging locker',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r230','qc-reference-c2026','Study','Hanging locker','Damage','Visible hole at forward top inch of hanging locker',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r231','qc-reference-c2026','Study','Draw locker','Operational','Drawer not soft closing + adjust gaps on outboard drawers',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r232','qc-reference-c2026','Study','Draw locker','Operational','Inboard drawers open while rolling + shaving',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r233','qc-reference-c2026','Study','Floor','Sealer','Neaten floor sealer',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r234','qc-reference-c2026','Study','Sliding entrance door with lock','Loose','Loose screws on sliding door',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r259','qc-reference-c2026','Stbd Aft Cabin','Hanging locker','Operational','Hanging locker door knocks',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r260','qc-reference-c2026','Stbd Aft Cabin','Hanging locker','Proud/Alignment','Fire label fitted skew',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r261','qc-reference-c2026','Stbd Aft Cabin','Vanity table/desk with storage locker and mirror under lid','Loose','Loose hinges at study desk',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r262','qc-reference-c2026','Stbd Aft Cabin','Vanity table/desk with storage locker and mirror under lid','Proud/Alignment','Skew push lock at study desk',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r263','qc-reference-c2026','Stbd Aft Cabin','Window blinds','Operational','Twisted blind strings',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r264','qc-reference-c2026','Stbd Aft Cabin','Fan','Incorrect','Rubber fitted incorrect on hatch',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r265','qc-reference-c2026','Stbd Aft Cabin','Inboard liner','Repairs','Poor repair on inboard ceiling liner',1,'Gelcoat',false,'','','','',''),
  ('qc-source-c2026-qc3-r266','qc-reference-c2026','Stbd Aft Cabin','Light switch','Proud/Alignment','Skew light switch',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r267','qc-reference-c2026','Stbd Aft Cabin','AC Outlets','Proud/Alignment','Skew outlets',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r268','qc-reference-c2026','Stbd Aft Cabin','2 x LED reading lamps over bunk','Loose','Loose reading lights at swivel',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r269','qc-reference-c2026','Stbd Aft Cabin','Hatch','Damage','Damage on anodising at deck hatch',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r296','qc-reference-c2026','Port Aft Cabin','Deck flange','Repairs','Poor repairs around going flange',1,'Gelcoat',false,'','','','',''),
  ('qc-source-c2026-qc3-r297','qc-reference-c2026','Port Aft Cabin','Doors','Missing part','Fit gullwing door locks and set door',4,'Deckfitting',false,'','','','',''),
  ('qc-source-c2026-qc3-r298','qc-reference-c2026','Port Aft Cabin','Window blinds','Proud/Alignment','Gullwing blind fitted skew in closed position',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r299','qc-reference-c2026','Port Aft Cabin','Vents','Damage','Poor spray on vent',9,'Spray Painting',false,'','','','',''),
  ('qc-source-c2026-qc3-r300','qc-reference-c2026','Port Aft Cabin','Hanging locker','Proud/Alignment','Stepping hanging locker front',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r301','qc-reference-c2026','Port Aft Cabin','Hanging locker','Loose','Loose catches on hanging lockers',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r302','qc-reference-c2026','Port Aft Cabin','Hanging locker','Missing part','Missing hanging rail inside hanging locker',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r303','qc-reference-c2026','Port Aft Cabin','Staircase','Damage','Deep scratches on stainless steel step covers',1,'Gelcoat',false,'','','','',''),
  ('qc-source-c2026-qc3-r304','qc-reference-c2026','Port Aft Cabin','Formica Bulkheads','Damage','Damage on edging outboard bottom step',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r305','qc-reference-c2026','Port Aft Cabin','Fan','Incorrect','Rubber fitted incorrect on fan',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r306','qc-reference-c2026','Port Aft Cabin','2 x LED reading lamps over bunk','Loose','Loose reading lights at swivel',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r307','qc-reference-c2026','Port Aft Cabin','Waste tank','Loose','Loose catch on waste tank locker',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r308','qc-reference-c2026','Port Aft Cabin','Bunktop/Double berth','Damage','Multiple screw holes on top bunk',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r309','qc-reference-c2026','Port Aft Cabin','Window blinds','Operational','Blind knocking outlet when closing',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r310','qc-reference-c2026','Port Aft Cabin','Draw locker','Cleaning','Overspray outboard of bunk drawer',10,'Cleaning',false,'','','','',''),
  ('qc-source-c2026-qc3-r333','qc-reference-c2026','Port Aft Heads','Sliding or hinged heads door','Missing part','Fit catch and adjust sliding heads door',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r334','qc-reference-c2026','Port Aft Heads','Door frames','Damage','Poor spray work on entire capping',9,'Spray Painting',false,'','','','',''),
  ('qc-source-c2026-qc3-r335','qc-reference-c2026','Port Aft Heads','Double towel rail','Loose','Towel rail loose making noise',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r336','qc-reference-c2026','Port Aft Heads','window module','Sealer','Seal around entire window transition',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r337','qc-reference-c2026','Port Aft Heads','Portlight with roller blind','Loose','Roller blind loose',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r338','qc-reference-c2026','Port Aft Heads','Electric sea water flush toilet','Loose','Loose toilet seat',5,'Plumbing',false,'','','','',''),
  ('qc-source-c2026-qc3-r339','qc-reference-c2026','Port Aft Heads','Under-basin locker with toilet roll holder','Damage','Damage to formica board inside under basin locker aft area',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r340','qc-reference-c2026','Port Aft Heads','Floor','Track repair','Poor tracking edge at toilet seat base',1,'Gelcoat',false,'','','','',''),
  ('qc-source-c2026-qc3-r373','qc-reference-c2026','Port Side Deck','Decklid','Damage','Chips on deck lid at aft Grabrail',1,'Gelcoat',false,'','','','',''),
  ('qc-source-c2026-qc3-r374','qc-reference-c2026','Port Side Deck','Decklid','Scratches','Scratches and dull on entire deck lid',1,'Gelcoat',false,'','','','',''),
  ('qc-source-c2026-qc3-r375','qc-reference-c2026','Port Side Deck','Midship area','Repair','Poor repair aft of midship cabin deck hatch',1,'Gelcoat',false,'','','','',''),
  ('qc-source-c2026-qc3-r376','qc-reference-c2026','Port Side Deck','Deck flange','Repair','Poor repair at deck joint at pulpit seat',1,'Gelcoat',false,'','','','',''),
  ('qc-source-c2026-qc3-r377','qc-reference-c2026','Port Side Deck','Bows','Crack','Crack and pour repair on entire bow',1,'Gelcoat',false,'','','','',''),
  ('qc-source-c2026-qc3-r382','qc-reference-c2026','Stbd Side Deck','Bows','Repair','Poor repair around entire bow more surface',1,'Gelcoat',false,'','','','',''),
  ('qc-source-c2026-qc3-r383','qc-reference-c2026','Stbd Side Deck','Deck flange','Scratches','Scratches and dull on entire toe rail',1,'Gelcoat',false,'','','','',''),
  ('qc-source-c2026-qc3-r384','qc-reference-c2026','Stbd Side Deck','Decklid','Scratches','Scratches and dull on entire deck lid',1,'Gelcoat',false,'','','','',''),
  ('qc-source-c2026-qc3-r385','qc-reference-c2026','Stbd Side Deck','Fwd area','Crack','Crack at spinlock',1,'Gelcoat',false,'','','','',''),
  ('qc-source-c2026-qc3-r386','qc-reference-c2026','Stbd Side Deck','Decklid','Repair','Thin on decklid above targawing',1,'Gelcoat',false,'','','','',''),
  ('qc-source-c2026-qc3-r406','qc-reference-c2026','Stbd Hull','Deck flange','Repair','Poor repair at Deck Joint at Transom',1,'Gelcoat',false,'','','','',''),
  ('qc-source-c2026-qc3-r407','qc-reference-c2026','Stbd Hull','Deck flange','Repair','Poor repair at Aft Deck Joint at Diesel Cap',1,'Gelcoat',false,'','','','',''),
  ('qc-source-c2026-qc3-r408','qc-reference-c2026','Stbd Hull','Aft area','Repairs','Poor repair at Aft chafeplate',1,'Gelcoat',false,'','','','',''),
  ('qc-source-c2026-qc3-r409','qc-reference-c2026','Stbd Hull','Aft area','Repair','Poor repair Aft of Aft Window',1,'Gelcoat',false,'','','','',''),
  ('qc-source-c2026-qc3-r410','qc-reference-c2026','Stbd Hull','Deck flange','Repair','Poor repair at Deck Joint at Stanchion Gate',1,'Gelcoat',false,'','','','',''),
  ('qc-source-c2026-qc3-r411','qc-reference-c2026','Stbd Hull','Deck flange','Damage','Grind marks Aft of Chain Plate Cover at Deck Joint',1,'Gelcoat',false,'','','','',''),
  ('qc-source-c2026-qc3-r412','qc-reference-c2026','Stbd Hull','Midship area','Sealer','Neaten Chain Plate Sealer',4,'Deckfitting',false,'','','','',''),
  ('qc-source-c2026-qc3-r413','qc-reference-c2026','Stbd Hull','Midship area','Repair','Poor repair Aft of Chain Plate Cover',1,'Gelcoat',false,'','','','',''),
  ('qc-source-c2026-qc3-r414','qc-reference-c2026','Stbd Hull','Deck flange','Repair','Poor repair at Deck Joint at Midship Cleat',1,'Gelcoat',false,'','','','',''),
  ('qc-source-c2026-qc3-r415','qc-reference-c2026','Stbd Hull','Deck flange','Repairs','Poor repair at Deck Joint between second and third Stanchion',1,'Gelcoat',false,'','','','',''),
  ('qc-source-c2026-qc3-r416','qc-reference-c2026','Stbd Hull','Midship area','Scratches','Scratches above Hull windows',1,'Gelcoat',false,'','','','',''),
  ('qc-source-c2026-qc3-r417','qc-reference-c2026','Stbd Hull','Hull windows','Damage','Clean and scratches on all Hull windows',8,'Perspex/Windows',false,'','','','',''),
  ('qc-source-c2026-qc3-r442','qc-reference-c2026','Forepeak','Holding tanks','Missing part','missing edging on waste tank locker',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r443','qc-reference-c2026','Forepeak','Holding tanks','Flowcoat','poor flowcoat above water tank flange',1,'Gelcoat',false,'','','','',''),
  ('qc-source-c2026-qc3-r444','qc-reference-c2026','Forepeak','Deck flange','Cleaning','clean spills on wiring sleeves below hatch',10,'Cleaning',false,'','','','',''),
  ('qc-source-c2026-qc3-r445','qc-reference-c2026','Forepeak','Floating step','Cleaning','clean entire floating step',10,'Cleaning',false,'','','','',''),
  ('qc-source-c2026-qc3-r446','qc-reference-c2026','Forepeak','Fwd area','Missing part','missing edging at fwd shelf + remove masking tape',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r447','qc-reference-c2026','Forepeak','Aircon unit','Missing part','damage + missing insulation at aircon',5,'Plumbing',false,'','','','',''),
  ('qc-source-c2026-qc3-r448','qc-reference-c2026','Forepeak','Bilges','Cleaning','spills on entire bilge surround',1,'Gelcoat',false,'','','','',''),
  ('qc-source-c2026-qc3-r478','qc-reference-c2026','Port Fwd Cabin','Cabin Door','Damage','damage + loose poppers on headboard',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r479','qc-reference-c2026','Port Fwd Cabin','Bunktop/Double berth','Damage','bunk top lid not sealer around',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r480','qc-reference-c2026','Port Fwd Cabin','Vinyl ceiling','Cleaning','clean all vynil panels',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r481','qc-reference-c2026','Port Fwd Cabin','Bunktop/Double berth','Repairs','neaten fibreglass tabbing inside bunk surround',1,'Gelcoat',false,'','','','',''),
  ('qc-source-c2026-qc3-r482','qc-reference-c2026','Port Fwd Cabin','Bunktop/Double berth','Loose','loose bunk Fiddle (check both)',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r483','qc-reference-c2026','Port Fwd Cabin','Bunktop/Double berth','Loose','loose fire extinguisher bracket',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r484','qc-reference-c2026','Port Fwd Cabin','window surround','Cleaning','clean spills on entire window surround',1,'Gelcoat',false,'','','','',''),
  ('qc-source-c2026-qc3-r485','qc-reference-c2026','Port Fwd Cabin','Bunktop/Double berth','Cleaning','clean excess on bunk top inboard side',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r486','qc-reference-c2026','Port Fwd Cabin','Bunk Drawers','Operational','top bunk drawer opening when locked',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r487','qc-reference-c2026','Port Fwd Cabin','Floor','Sealer','poor sealer on entire floor joints + remove spills on entire floor',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r488','qc-reference-c2026','Port Fwd Cabin','Window blinds','Cleaning','compound on cabin blinds (check entire)',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r489','qc-reference-c2026','Port Fwd Cabin','Fan','Missing part','missing fan wiring cut out',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r490','qc-reference-c2026','Port Fwd Cabin','Formica Bulkheads','Damage','missing touch up on Formica joints on outboard bulkhead + sealer',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r491','qc-reference-c2026','Port Fwd Cabin','Coat hook','Loose','loose coat hook base',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r492','qc-reference-c2026','Port Fwd Cabin','Light switch','Loose','loose light switch inboard side',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r493','qc-reference-c2026','Port Fwd Cabin','Magazine locker/shelf locker','Loose','loose bookshelf rails above inboard hanging locker',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r494','qc-reference-c2026','Port Fwd Cabin','Hanging locker','Loose','loos catches on hanging locker door',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r495','qc-reference-c2026','Port Fwd Cabin','Solids','Damage','damage door capping on entire door cappings',9,'Spray Painting',false,'','','','',''),
  ('qc-source-c2026-qc3-r496','qc-reference-c2026','Port Fwd Cabin','Cabin Door','Missing part','missing sticker player on cabin door',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r513','qc-reference-c2026','Port Fwd Heads','Formica Bulkheads','Sealer','missing + damage+ yellow sealer on entire heads surround',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r514','qc-reference-c2026','Port Fwd Heads','Sliding entrance door with lock','Sealer','missing sealer above at heads door + below door frame',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r515','qc-reference-c2026','Port Fwd Heads','Sliding entrance door with lock','missing','missing striker plate on heads door',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r516','qc-reference-c2026','Port Fwd Heads','Hatch','cleaning','clean hatch surround',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r517','qc-reference-c2026','Port Fwd Heads','Fold up vanity mirror','loose','loose Formica strip fwd of vanity locker',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r518','qc-reference-c2026','Port Fwd Heads','Window blinds','loose','loose blind tac',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r519','qc-reference-c2026','Port Fwd Heads','Windows','scratches','hull window + portlight',8,'Perspex/Windows',false,'','','','',''),
  ('qc-source-c2026-qc3-r520','qc-reference-c2026','Port Fwd Heads','Under-basin locker with toilet roll holder','missing','missing toilet roll holder',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r521','qc-reference-c2026','Port Fwd Heads','Under-basin locker with toilet roll holder','loose','loose catch on basin locker',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r522','qc-reference-c2026','Port Fwd Heads','Perspex','loose','loose Perspex divider',3,'Joinery/Carp',false,'','','','','')
on conflict (id) do nothing;
insert into public.quality_control_defects (id,boat_id,area_name,item,failure_mode,description,code,discipline,concern,repaired_by,repaired_date,team_leader_check,qc_rwk,qc_acc) values
  ('qc-source-c2026-qc3-r523','qc-reference-c2026','Port Fwd Heads','Vanity locker with mirror','loose','loose vanity locker catch',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r524','qc-reference-c2026','Port Fwd Heads','Shower bulkhead module','Loose','loose shower rose base',5,'Plumbing',false,'','','','',''),
  ('qc-source-c2026-qc3-r528','qc-reference-c2026','Port Passage','Floor','sealer','poor sealer on entire passage floor',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r529','qc-reference-c2026','Port Passage','Nav desk','cleaning','clean spills below settee surrounds',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r530','qc-reference-c2026','Port Passage','Stowage space under floorboards','proud','passage floorboards warped',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r531','qc-reference-c2026','Port Passage','Staircase','loose','lose fire extinguisher bracket',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r532','qc-reference-c2026','Port Passage','Cabin Door','sealer','missing sealer at mid outboard capping',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r551','qc-reference-c2026','Port Mid Cabin','Cabin Door','Missing part','missing screws on door capping',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r552','qc-reference-c2026','Port Mid Cabin','Cabin Door','Missing part','striker plate on door',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r553','qc-reference-c2026','Port Mid Cabin','Floor','Sealer','poor sealer on cabin floor+outboard bunk joints + clean spills on entire floor',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r554','qc-reference-c2026','Port Mid Cabin','Formica Bulkheads','Loose','poor touch up on outboard Formica jointss',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r555','qc-reference-c2026','Port Mid Cabin','Hanging locker','Loose','catch on hanging locker door',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r556','qc-reference-c2026','Port Mid Cabin','Fan','Missing part','missing cut out on fan base at wiring',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r557','qc-reference-c2026','Port Mid Cabin','window surround','Damage','bubbles on window surround',9,'Spray Painting',true,'','','','',''),
  ('qc-source-c2026-qc3-r558','qc-reference-c2026','Port Mid Cabin','2 x LED reading lamps over bunk','Cleaning','remove pencil markings at headboard reading light',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r559','qc-reference-c2026','Port Mid Cabin','Vinyl panels','Cleaning','clean all vynil panels + remove pencil markings on panels',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r564','qc-reference-c2026','Port Mid Heads','Floor','Loose','floor tracking creeking when stepped on',1,'Gelcoat',true,'','','','',''),
  ('qc-source-c2026-qc3-r565','qc-reference-c2026','Port Mid Heads','Sliding or hinged heads door','Missing part','striker plate on heads door',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r566','qc-reference-c2026','Port Mid Heads','Hatch','Operational','hatch liner magnet not catching',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r567','qc-reference-c2026','Port Mid Heads','Shower bulkhead module','Sealer','missing sealer on bulkhead inboard joint',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r568','qc-reference-c2026','Port Mid Heads','Sliding entrance door with lock','Damage','on screw holes on heads door',9,'Spray Painting',false,'','','','',''),
  ('qc-source-c2026-qc3-r569','qc-reference-c2026','Port Mid Heads','Sliding or hinged heads door','Cleaning','clean entire heads door',3,'Joinery/Carp',false,'','','','',''),
  ('qc-source-c2026-qc3-r587','qc-reference-c2026','Flybridge','Floating step','Scratches','dull on all Flybridge steps coamings',1,'Gelcoat',false,'','','','',''),
  ('qc-source-c2026-qc3-r588','qc-reference-c2026','Flybridge','Bimini','Scratches','dull on entire Bimini surround + flange',1,'Gelcoat',false,'','','','',''),
  ('qc-source-c2026-qc3-r589','qc-reference-c2026','Flybridge','Bimini','Scratches','On Bimini skyscreen',8,'Perspex/Windows',false,'','','','',''),
  ('qc-source-c2026-qc3-r590','qc-reference-c2026','Flybridge','Aft area','Spills','spills on tracking aft at stern light tracking',1,'Gelcoat',false,'','','','',''),
  ('qc-source-c2026-qc3-r591','qc-reference-c2026','Flybridge','Main boom topping lift','Missing part','missing Boom labels',4,'Deckfitting',false,'','','','',''),
  ('qc-source-c2026-qc3-r592','qc-reference-c2026','Flybridge','Floor','Cleaning','clean entire tracking at mast',1,'Gelcoat',false,'','','','',''),
  ('qc-source-c2026-qc3-r597','qc-reference-c2026','Fwd Cockpit & Foredeck','Floor','Loose','fwd cockpit sumo lid wobbly',4,'Deckfitting',false,'','','','',''),
  ('qc-source-c2026-qc3-r598','qc-reference-c2026','Fwd Cockpit & Foredeck','Fwd cockpit door','Loose','loose catch on settee',4,'Deckfitting',false,'','','','',''),
  ('qc-source-c2026-qc3-r599','qc-reference-c2026','Fwd Cockpit & Foredeck','U shape settee','Spills','spills on STB settee tracking',1,'Gelcoat',false,'','','','',''),
  ('qc-source-c2026-qc3-r600','qc-reference-c2026','Fwd Cockpit & Foredeck','Vinyl ceiling','Loose','loose vynil ceiling panels + clean all',4,'Deckfitting',false,'','','','',''),
  ('qc-source-c2026-qc3-r601','qc-reference-c2026','Fwd Cockpit & Foredeck','Vinyl','Damage','centre vynil panel',4,'Deckfitting',false,'','','','',''),
  ('qc-source-c2026-qc3-r602','qc-reference-c2026','Fwd Cockpit & Foredeck','Ceiling','Repairs','mould marks aft of ceiling coaming joints fwd of main window',1,'Gelcoat',false,'','','','',''),
  ('qc-source-c2026-qc3-r603','qc-reference-c2026','Fwd Cockpit & Foredeck','Ceiling','Repairs','poor repairs + scratches on decklid coaming',1,'Gelcoat',false,'','','','',''),
  ('qc-source-c2026-qc3-r604','qc-reference-c2026','Fwd Cockpit & Foredeck','Anchor/windlass locker','Operational','anchor locker not operating when locking',4,'Deckfitting',false,'','','','',''),
  ('qc-source-c2026-qc3-r605','qc-reference-c2026','Fwd Cockpit & Foredeck','Locker lids','Proud/Alignment','generator locker lid stepping when locked',4,'Deckfitting',false,'','','','',''),
  ('qc-source-c2026-qc3-r606','qc-reference-c2026','Fwd Cockpit & Foredeck','Trampoline','Loose','loose trampoline+ tension lines',4,'Deckfitting',false,'','','','',''),
  ('qc-source-c2026-qc3-r607','qc-reference-c2026','Fwd Cockpit & Foredeck','Natural anodized crossbeam c/w mooring cleats','Sealer','missing sealer at nav light A-frame',4,'Deckfitting',false,'','','','',''),
  ('qc-source-c2026-qc3-r608','qc-reference-c2026','Fwd Cockpit & Foredeck','Settee','Cracks','outboard of main window in waterline',1,'Gelcoat',false,'','','','',''),
  ('qc-source-c2026-qc3-r609','qc-reference-c2026','Fwd Cockpit & Foredeck','Guard wires across bow and stern','Loose','loose gaurdwires+ clean crossbeam',4,'Deckfitting',false,'','','','','')
on conflict (id) do nothing;
commit;
select count(*) as imported_quality_control_defects from public.quality_control_defects;
