-- Fill only blank Quality Control area inspectors extracted from the supplied audit workbooks.
-- Existing inspector assignments are deliberately preserved.
begin;
update public.quality_control_areas set inspector='Jodi Jackson', updated_at=now() where boat_id='qc-reference-b8126' and area_name='Saloon' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Jodi Jackson', updated_at=now() where boat_id='qc-reference-b8126' and area_name='Port Passage' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Jodi Jackson', updated_at=now() where boat_id='qc-reference-b8126' and area_name='Port Fwd Heads' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Mogamat Yunis Jabaar', updated_at=now() where boat_id='qc-reference-b8126' and area_name='Stbd Aft Heads' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Mogamat Yunis Jabaar', updated_at=now() where boat_id='qc-reference-b8126' and area_name='Stbd Fwd Cabin' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Jodi Jackson', updated_at=now() where boat_id='qc-reference-b8126' and area_name='Aft Cockpit' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Jodi Jackson', updated_at=now() where boat_id='qc-reference-b8126' and area_name='Stbd Engine Room' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Mogamat Yunis Jabaar', updated_at=now() where boat_id='qc-reference-b8126' and area_name='Fwd Cockpit & Foredeck' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Jodi Jackson', updated_at=now() where boat_id='qc-reference-b8126' and area_name='Flybridge' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Jodi Jackson', updated_at=now() where boat_id='qc-reference-b8126' and area_name='Port Hull' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Jodi Jackson', updated_at=now() where boat_id='qc-reference-b8127' and area_name='Saloon' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Jodi Jackson', updated_at=now() where boat_id='qc-reference-b8127' and area_name='Port Fwd Heads' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Jodi Jackson', updated_at=now() where boat_id='qc-reference-b8127' and area_name='Stbd Fwd Heads' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Jodi Jackson', updated_at=now() where boat_id='qc-reference-b8127' and area_name='Aft Cockpit' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Jodi Jackson', updated_at=now() where boat_id='qc-reference-b8127' and area_name='Port Engine Room' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Jodi Jackson', updated_at=now() where boat_id='qc-reference-b8127' and area_name='Fwd Cockpit & Foredeck' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Jodi Jackson', updated_at=now() where boat_id='qc-reference-b8127' and area_name='Flybridge' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Jodi Jackson', updated_at=now() where boat_id='qc-reference-b8128' and area_name='Saloon' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Jodi Jackson', updated_at=now() where boat_id='qc-reference-b8128' and area_name='Owner''S Heads' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Jodi Jackson', updated_at=now() where boat_id='qc-reference-b8128' and area_name='Port Aft Heads' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Jodi Jackson', updated_at=now() where boat_id='qc-reference-b8128' and area_name='Port Engine Room' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Jodi Jackson', updated_at=now() where boat_id='qc-reference-b8128' and area_name='Flybridge' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Jodi Jackson', updated_at=now() where boat_id='qc-reference-b8128' and area_name='Stbd Hull' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Jodi Jackson', updated_at=now() where boat_id='qc-reference-b8129' and area_name='Saloon' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Jodi Jackson', updated_at=now() where boat_id='qc-reference-b8129' and area_name='Port Fwd Heads' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Jodi Jackson', updated_at=now() where boat_id='qc-reference-b8129' and area_name='Owner''S Heads' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Jodi Jackson', updated_at=now() where boat_id='qc-reference-b8129' and area_name='Aft Cockpit' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Mogamat Yunis Jabaar', updated_at=now() where boat_id='qc-reference-b8129' and area_name='Fwd Cockpit & Foredeck' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Jodi Jackson', updated_at=now() where boat_id='qc-reference-b8129' and area_name='Port Hull' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Jodi Jackson', updated_at=now() where boat_id='qc-reference-b8129' and area_name='Stbd Engine Room' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Jodi Jackson', updated_at=now() where boat_id='qc-reference-b8129' and area_name='Stbd Hull' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Jodi Jackson', updated_at=now() where boat_id='qc-reference-b8130' and area_name='Saloon' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Jodi Jackson', updated_at=now() where boat_id='qc-reference-b8130' and area_name='Port Passage' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Jodi Jackson', updated_at=now() where boat_id='qc-reference-b8130' and area_name='Port Fwd Heads' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Riyaaz Harold', updated_at=now() where boat_id='qc-reference-b8130' and area_name='Stbd Aft Cabin' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Jodi Jackson', updated_at=now() where boat_id='qc-reference-b8130' and area_name='Port Engine Room' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Riyaaz Harold', updated_at=now() where boat_id='qc-reference-b8130' and area_name='Fwd Cockpit & Foredeck' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Jodi Jackson', updated_at=now() where boat_id='qc-reference-b8130' and area_name='Port Hull' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Moegamat Saleem Philander', updated_at=now() where boat_id='qc-reference-b8130' and area_name='Flybridge' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Imtiyaaz Hassan Hoosain', updated_at=now() where boat_id='qc-reference-b9074' and area_name='Saloon' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Imtiyaaz Hassan Hoosain', updated_at=now() where boat_id='qc-reference-b9074' and area_name='Stb Heads' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Imran Majiet', updated_at=now() where boat_id='qc-reference-b9074' and area_name='Port Heads' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Imtiyaaz Hassan Hoosain', updated_at=now() where boat_id='qc-reference-b9074' and area_name='Stbd Engine Room' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Imran Majiet', updated_at=now() where boat_id='qc-reference-b9074' and area_name='Fwd Cockpit & Foredeck' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Imran Majiet', updated_at=now() where boat_id='qc-reference-b9074' and area_name='Stbd Side Deck' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Imtiyaaz Hassan Hoosain', updated_at=now() where boat_id='qc-reference-b9074' and area_name='Port Hull' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Imtiyaaz Hassan Hoosain', updated_at=now() where boat_id='qc-reference-b9075' and area_name='Saloon' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Kyle Carl Adams', updated_at=now() where boat_id='qc-reference-b9075' and area_name='Stbd Study & Passage' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Kyle Carl Adams', updated_at=now() where boat_id='qc-reference-b9075' and area_name='Owner''S Heads' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Imran Majiet', updated_at=now() where boat_id='qc-reference-b9075' and area_name='Port Heads' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Imran Majiet', updated_at=now() where boat_id='qc-reference-b9075' and area_name='Port Aft Cabin' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Imtiyaaz Hassan Hoosain', updated_at=now() where boat_id='qc-reference-b9075' and area_name='Stbd Engine Room' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Imran Majiet', updated_at=now() where boat_id='qc-reference-b9075' and area_name='Flybridge' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Imran Majiet', updated_at=now() where boat_id='qc-reference-b9075' and area_name='Fwd Cockpit & Foredeck' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Imtiyaaz Hassan Hoosain', updated_at=now() where boat_id='qc-reference-b9075' and area_name='Stbd Hull' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Imtiyaaz Hassan Hoosain', updated_at=now() where boat_id='qc-reference-b9076' and area_name='Saloon' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Mogamat Yunis Jabaar', updated_at=now() where boat_id='qc-reference-b9076' and area_name='Port Passage' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Mogamat Yunis Jabaar', updated_at=now() where boat_id='qc-reference-b9076' and area_name='Port Fwd Cabin' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Mogamat Yunis Jabaar', updated_at=now() where boat_id='qc-reference-b9076' and area_name='Stbd Aft Cabin' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Imtiyaaz Hassan Hoosain', updated_at=now() where boat_id='qc-reference-b9076' and area_name='Stbd Engine Room' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Mogamat Yunis Jabaar', updated_at=now() where boat_id='qc-reference-b9076' and area_name='Port Side Deck' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Mogamat Yunis Jabaar', updated_at=now() where boat_id='qc-reference-b9076' and area_name='Flybridge' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Jodi Jackson', updated_at=now() where boat_id='qc-reference-b9076' and area_name='Port Hull' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Jodi Jackson', updated_at=now() where boat_id='qc-reference-b9077' and area_name='Saloon' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Mogamat Yunis Jabaar', updated_at=now() where boat_id='qc-reference-b9077' and area_name='Port Heads' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Mogamat Yunis Jabaar', updated_at=now() where boat_id='qc-reference-b9077' and area_name='Port Aft Cabin' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Imtiyaaz Hassan Hoosain', updated_at=now() where boat_id='qc-reference-b9077' and area_name='Owner''S Heads' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Jodi Jackson', updated_at=now() where boat_id='qc-reference-b9077' and area_name='Aft Cockpit' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Jodi Jackson', updated_at=now() where boat_id='qc-reference-b9077' and area_name='Fwd Cockpit & Foredeck' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Jodi Jackson', updated_at=now() where boat_id='qc-reference-b9077' and area_name='Flybridge' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Jodi Jackson', updated_at=now() where boat_id='qc-reference-b9077' and area_name='Port Engine Room' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Jodi Jackson', updated_at=now() where boat_id='qc-reference-b9077' and area_name='Port Hull' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Jodi Jackson', updated_at=now() where boat_id='qc-reference-b9078' and area_name='Saloon' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Jodi Jackson', updated_at=now() where boat_id='qc-reference-b9078' and area_name='Owner''S Heads' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Jodi Jackson', updated_at=now() where boat_id='qc-reference-b9078' and area_name='Port Fwd Cabin' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Jodi Jackson', updated_at=now() where boat_id='qc-reference-b9078' and area_name='Aft Cockpit' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Jodi Jackson', updated_at=now() where boat_id='qc-reference-b9078' and area_name='Fwd Cockpit & Foredeck' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Jodi Jackson', updated_at=now() where boat_id='qc-reference-b9078' and area_name='Flybridge' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Jodi Jackson', updated_at=now() where boat_id='qc-reference-b9078' and area_name='Port Hull' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Mogamat Yunis Jabaar', updated_at=now() where boat_id='qc-reference-c1071' and area_name='Saloon' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Mogamat Yunis Jabaar', updated_at=now() where boat_id='qc-reference-c1071' and area_name='Port Aft Cabin' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Mogamat Yunis Jabaar', updated_at=now() where boat_id='qc-reference-c1071' and area_name='Port Aft Heads' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Mogamat Yunis Jabaar', updated_at=now() where boat_id='qc-reference-c1071' and area_name='Port Passage' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Imtiyaaz Hassan Hoosain', updated_at=now() where boat_id='qc-reference-c1071' and area_name='Port Fwd Cabin' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Imtiyaaz Hassan Hoosain', updated_at=now() where boat_id='qc-reference-c1071' and area_name='Port Fwd Heads' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Imtiyaaz Hassan Hoosain', updated_at=now() where boat_id='qc-reference-c1071' and area_name='Study' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Imtiyaaz Hassan Hoosain', updated_at=now() where boat_id='qc-reference-c1071' and area_name='Stbd Fwd Cabin' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Imtiyaaz Hassan Hoosain', updated_at=now() where boat_id='qc-reference-c1071' and area_name='Stbd Fwd Heads' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Mogamat Yunis Jabaar', updated_at=now() where boat_id='qc-reference-c1071' and area_name='Aft Cockpit' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Mogamat Yunis Jabaar', updated_at=now() where boat_id='qc-reference-c1071' and area_name='Port Engine Room' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Imtiyaaz Hassan Hoosain', updated_at=now() where boat_id='qc-reference-c1071' and area_name='Fwd Cockpit & Foredeck' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Imtiyaaz Hassan Hoosain', updated_at=now() where boat_id='qc-reference-c1071' and area_name='Flybridge' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Mogamat Yunis Jabaar', updated_at=now() where boat_id='qc-reference-c1071' and area_name='Port Hull' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Imtiyaaz Hassan Hoosain', updated_at=now() where boat_id='qc-reference-c1071' and area_name='Stbd Hull' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Imtiyaaz Hassan Hoosain', updated_at=now() where boat_id='qc-reference-c1073' and area_name='Saloon' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Imtiyaaz Hassan Hoosain', updated_at=now() where boat_id='qc-reference-c1073' and area_name='Stbd Fwd Cabin' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Imtiyaaz Hassan Hoosain', updated_at=now() where boat_id='qc-reference-c1073' and area_name='Stbd Fwd Heads' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Mogamat Yunis Jabaar', updated_at=now() where boat_id='qc-reference-c1073' and area_name='Owner''S Heads' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Mogamat Yunis Jabaar', updated_at=now() where boat_id='qc-reference-c1073' and area_name='Stbd Study & Passage' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Mogamat Yunis Jabaar', updated_at=now() where boat_id='qc-reference-c1073' and area_name='Stbd Aft Cabin' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Mogamat Yunis Jabaar', updated_at=now() where boat_id='qc-reference-c1073' and area_name='Port Aft Cabin' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Mogamat Yunis Jabaar', updated_at=now() where boat_id='qc-reference-c1073' and area_name='Port Aft Heads' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Mogamat Yunis Jabaar', updated_at=now() where boat_id='qc-reference-c1073' and area_name='Port Passage' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Mogamat Yunis Jabaar', updated_at=now() where boat_id='qc-reference-c1073' and area_name='Port Fwd Heads' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Mogamat Yunis Jabaar', updated_at=now() where boat_id='qc-reference-c1073' and area_name='Port Fwd Cabin' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Imtiyaaz Hassan Hoosain', updated_at=now() where boat_id='qc-reference-c1073' and area_name='Aft Cockpit' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Imtiyaaz Hassan Hoosain', updated_at=now() where boat_id='qc-reference-c1073' and area_name='Port Engine Room' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Mogamat Yunis Jabaar', updated_at=now() where boat_id='qc-reference-c1073' and area_name='Port Side Deck' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Mogamat Yunis Jabaar', updated_at=now() where boat_id='qc-reference-c1073' and area_name='Flybridge' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Mogamat Yunis Jabaar', updated_at=now() where boat_id='qc-reference-c1073' and area_name='Fwd Cockpit & Foredeck' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Mogamat Yunis Jabaar', updated_at=now() where boat_id='qc-reference-c1073' and area_name='Port Hull' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Imtiyaaz Hassan Hoosain', updated_at=now() where boat_id='qc-reference-c1073' and area_name='Stbd Hull' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Imtiyaaz Hassan Hoosain', updated_at=now() where boat_id='qc-reference-c1074' and area_name='Saloon' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Imtiyaaz Hassan Hoosain', updated_at=now() where boat_id='qc-reference-c1074' and area_name='Study' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Imtiyaaz Hassan Hoosain', updated_at=now() where boat_id='qc-reference-c1074' and area_name='Owner''S Heads' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Imtiyaaz Hassan Hoosain', updated_at=now() where boat_id='qc-reference-c1074' and area_name='Stbd Fwd Cabin' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Imtiyaaz Hassan Hoosain', updated_at=now() where boat_id='qc-reference-c1074' and area_name='Stbd Fwd Heads' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Mogamat Yunis Jabaar', updated_at=now() where boat_id='qc-reference-c1074' and area_name='Port Aft Cabin' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Mogamat Yunis Jabaar', updated_at=now() where boat_id='qc-reference-c1074' and area_name='Port Aft Heads' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Mogamat Yunis Jabaar', updated_at=now() where boat_id='qc-reference-c1074' and area_name='Port Passage' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Mogamat Yunis Jabaar', updated_at=now() where boat_id='qc-reference-c1074' and area_name='Port Fwd Heads' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Mogamat Yunis Jabaar', updated_at=now() where boat_id='qc-reference-c1074' and area_name='Port Fwd Cabin' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Imtiyaaz Hassan Hoosain', updated_at=now() where boat_id='qc-reference-c1074' and area_name='Aft Cockpit' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Imtiyaaz Hassan Hoosain', updated_at=now() where boat_id='qc-reference-c1074' and area_name='Stbd Engine Room' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Mogamat Yunis Jabaar', updated_at=now() where boat_id='qc-reference-c1074' and area_name='Port Side Deck' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Mogamat Yunis Jabaar', updated_at=now() where boat_id='qc-reference-c1074' and area_name='Fwd Cockpit & Foredeck' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Mogamat Yunis Jabaar', updated_at=now() where boat_id='qc-reference-c1074' and area_name='Flybridge' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Mogamat Yunis Jabaar', updated_at=now() where boat_id='qc-reference-c1074' and area_name='Stbd Hull' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Imtiyaaz Hassan Hoosain', updated_at=now() where boat_id='qc-reference-c1074' and area_name='A/S' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Imtiyaaz Hassan Hoosain', updated_at=now() where boat_id='qc-reference-c1074' and area_name='Port Hull' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Imtiyaaz Hassan Hoosain', updated_at=now() where boat_id='qc-reference-c1075' and area_name='Stbd Aft Cabin' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Imtiyaaz Hassan Hoosain', updated_at=now() where boat_id='qc-reference-c1075' and area_name='Study' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Imtiyaaz Hassan Hoosain', updated_at=now() where boat_id='qc-reference-c1075' and area_name='Owner''S Heads' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Imtiyaaz Hassan Hoosain', updated_at=now() where boat_id='qc-reference-c1075' and area_name='Stbd Passage' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Imtiyaaz Hassan Hoosain', updated_at=now() where boat_id='qc-reference-c1075' and area_name='Stbd Fwd Cabin' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Imtiyaaz Hassan Hoosain', updated_at=now() where boat_id='qc-reference-c1075' and area_name='Stbd Fwd Heads' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Mogamat Yunis Jabaar', updated_at=now() where boat_id='qc-reference-c1075' and area_name='Aft Cockpit' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Mogamat Yunis Jabaar', updated_at=now() where boat_id='qc-reference-c1075' and area_name='Stbd Engine Room' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Imtiyaaz Hassan Hoosain', updated_at=now() where boat_id='qc-reference-c1075' and area_name='Fwd Cockpit & Foredeck' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Imtiyaaz Hassan Hoosain', updated_at=now() where boat_id='qc-reference-c1075' and area_name='Stbd Side Deck' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Imtiyaaz Hassan Hoosain', updated_at=now() where boat_id='qc-reference-c1075' and area_name='Flybridge' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Imtiyaaz Hassan Hoosain', updated_at=now() where boat_id='qc-reference-c1075' and area_name='Port Hull' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Imtiyaaz Hassan Hoosain', updated_at=now() where boat_id='qc-reference-c1076' and area_name='Saloon' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Imtiyaaz Hassan Hoosain', updated_at=now() where boat_id='qc-reference-c1076' and area_name='Study' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Imtiyaaz Hassan Hoosain', updated_at=now() where boat_id='qc-reference-c1076' and area_name='Stbd Aft Heads' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Imtiyaaz Hassan Hoosain', updated_at=now() where boat_id='qc-reference-c1076' and area_name='Aft Cockpit' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Imtiyaaz Hassan Hoosain', updated_at=now() where boat_id='qc-reference-c1076' and area_name='Port Engine Room' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Mogamat Yunis Jabaar', updated_at=now() where boat_id='qc-reference-c1076' and area_name='Stbd Side Deck' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Mogamat Yunis Jabaar', updated_at=now() where boat_id='qc-reference-c1076' and area_name='Fwd Cockpit & Foredeck' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Kyle Carl Adams', updated_at=now() where boat_id='qc-reference-c2022' and area_name='Saloon' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Mogamat Yunis Jabaar', updated_at=now() where boat_id='qc-reference-c2022' and area_name='Stbd Fwd Heads' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Mogamat Yunis Jabaar', updated_at=now() where boat_id='qc-reference-c2022' and area_name='Stbd Passage' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Imran Majiet', updated_at=now() where boat_id='qc-reference-c2022' and area_name='Owner''S Heads' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Imran Majiet', updated_at=now() where boat_id='qc-reference-c2022' and area_name='Study' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Imran Majiet', updated_at=now() where boat_id='qc-reference-c2022' and area_name='Stbd Aft Cabin' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Imtiyaaz Hassan Hoosain', updated_at=now() where boat_id='qc-reference-c2022' and area_name='Port Fwd Heads' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Imtiyaaz Hassan Hoosain', updated_at=now() where boat_id='qc-reference-c2022' and area_name='Port Mid Cabin' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Imtiyaaz Hassan Hoosain', updated_at=now() where boat_id='qc-reference-c2022' and area_name='Port Mid Heads' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Kyle Carl Adams', updated_at=now() where boat_id='qc-reference-c2022' and area_name='Port Aft Cabin' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Imran Majiet', updated_at=now() where boat_id='qc-reference-c2022' and area_name='Aft Cockpit' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Imran Majiet', updated_at=now() where boat_id='qc-reference-c2022' and area_name='Stbd Engine Room' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Imtiyaaz Hassan Hoosain', updated_at=now() where boat_id='qc-reference-c2022' and area_name='Flybridge' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Mogamat Yunis Jabaar', updated_at=now() where boat_id='qc-reference-c2022' and area_name='Fwd Cockpit & Foredeck' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Kyle Carl Adams', updated_at=now() where boat_id='qc-reference-c2022' and area_name='Crew Quarters' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Kyle Carl Adams', updated_at=now() where boat_id='qc-reference-c2022' and area_name='Port Hull' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Kyle Carl Adams', updated_at=now() where boat_id='qc-reference-c2022' and area_name='Stbd Hull' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Imran Majiet', updated_at=now() where boat_id='qc-reference-c2023' and area_name='Saloon' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Sheldon Barends', updated_at=now() where boat_id='qc-reference-c2023' and area_name='Stbd Fwd Heads' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Sheldon Barends', updated_at=now() where boat_id='qc-reference-c2023' and area_name='Stbd Fwd Cabin' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Sheldon Barends', updated_at=now() where boat_id='qc-reference-c2023' and area_name='Stbd Passage' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Sheldon Barends', updated_at=now() where boat_id='qc-reference-c2023' and area_name='Stbd Aft Heads' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Sheldon Barends', updated_at=now() where boat_id='qc-reference-c2023' and area_name='Stbd Aft Cabin' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Sheldon Barends', updated_at=now() where boat_id='qc-reference-c2023' and area_name='Forepeak' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Kyle Carl Adams', updated_at=now() where boat_id='qc-reference-c2023' and area_name='Port Aft Heads' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Kyle Carl Adams', updated_at=now() where boat_id='qc-reference-c2023' and area_name='Port Aft Cabin' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Kyle Carl Adams', updated_at=now() where boat_id='qc-reference-c2023' and area_name='Port Passage' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Kyle Carl Adams', updated_at=now() where boat_id='qc-reference-c2023' and area_name='Port Fwd Cabin' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Kyle Carl Adams', updated_at=now() where boat_id='qc-reference-c2023' and area_name='Port Fwd Heads' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Sheldon Barends', updated_at=now() where boat_id='qc-reference-c2023' and area_name='Stbd Hull' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Kyle Carl Adams', updated_at=now() where boat_id='qc-reference-c2023' and area_name='Port Hull' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Imran Majiet', updated_at=now() where boat_id='qc-reference-c2023' and area_name='Flybridge' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Imran Majiet', updated_at=now() where boat_id='qc-reference-c2023' and area_name='Stbd Engine Room' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Sheldon Barends', updated_at=now() where boat_id='qc-reference-c2023' and area_name='Stbd Side Deck' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Sheldon Barends', updated_at=now() where boat_id='qc-reference-c2023' and area_name='Port Side Deck' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Sheldon Barends', updated_at=now() where boat_id='qc-reference-c2023' and area_name='Fwd Cockpit & Foredeck' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Kyle Carl Adams', updated_at=now() where boat_id='qc-reference-c2024' and area_name='Saloon' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Sheldon Barends', updated_at=now() where boat_id='qc-reference-c2024' and area_name='Stbd Fwd Heads' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Sheldon Barends', updated_at=now() where boat_id='qc-reference-c2024' and area_name='Stbd Passage' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Kyle Carl Adams', updated_at=now() where boat_id='qc-reference-c2024' and area_name='Owner''S Heads' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Kyle Carl Adams', updated_at=now() where boat_id='qc-reference-c2024' and area_name='Stbd Study & Passage' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Kyle Carl Adams', updated_at=now() where boat_id='qc-reference-c2024' and area_name='Stbd Aft Cabin' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Imran Majiet', updated_at=now() where boat_id='qc-reference-c2024' and area_name='Aft Cockpit' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Imran Majiet', updated_at=now() where boat_id='qc-reference-c2024' and area_name='Flybridge' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Imran Majiet', updated_at=now() where boat_id='qc-reference-c2024' and area_name='Port Engine Room' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Kyle Carl Adams', updated_at=now() where boat_id='qc-reference-c2024' and area_name='Stbd Hull' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Kyle Carl Adams', updated_at=now() where boat_id='qc-reference-c2024' and area_name='Port Hull' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Sheldon Barends', updated_at=now() where boat_id='qc-reference-c2025' and area_name='Saloon' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Sheldon Barends', updated_at=now() where boat_id='qc-reference-c2025' and area_name='Port Aft Heads' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Sheldon Barends', updated_at=now() where boat_id='qc-reference-c2025' and area_name='Crew Quarters' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Sheldon Barends', updated_at=now() where boat_id='qc-reference-c2025' and area_name='Fwd Cockpit & Foredeck' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Sheldon Barends', updated_at=now() where boat_id='qc-reference-c2025' and area_name='Aft Cockpit' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Sheldon Barends', updated_at=now() where boat_id='qc-reference-c2025' and area_name='Port Engine Room' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Sheldon Barends', updated_at=now() where boat_id='qc-reference-c2025' and area_name='Port Hull' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Sheldon Barends', updated_at=now() where boat_id='qc-reference-c2025' and area_name='Stbd Fwd Heads' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Sheldon Barends', updated_at=now() where boat_id='qc-reference-c2025' and area_name='Stbd Fwd Cabin' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Sheldon Barends', updated_at=now() where boat_id='qc-reference-c2025' and area_name='Stbd Passage' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Sheldon Barends', updated_at=now() where boat_id='qc-reference-c2025' and area_name='Stbd Aft Heads' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Sheldon Barends', updated_at=now() where boat_id='qc-reference-c2025' and area_name='Stbd Aft Cabin' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Sheldon Barends', updated_at=now() where boat_id='qc-reference-c2026' and area_name='Port Hull' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Kyle Carl Adams', updated_at=now() where boat_id='qc-reference-c2026' and area_name='Saloon' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Kyle Carl Adams', updated_at=now() where boat_id='qc-reference-c2026' and area_name='Aft Cockpit' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Kyle Carl Adams', updated_at=now() where boat_id='qc-reference-c2026' and area_name='Port Engine Room' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Kyle Carl Adams', updated_at=now() where boat_id='qc-reference-c2026' and area_name='Stbd Fwd Cabin' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Kyle Carl Adams', updated_at=now() where boat_id='qc-reference-c2026' and area_name='Stbd Passage' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Kyle Carl Adams', updated_at=now() where boat_id='qc-reference-c2026' and area_name='Owner''S Heads' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Kyle Carl Adams', updated_at=now() where boat_id='qc-reference-c5001' and area_name='Port Side Deck' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Kyle Carl Adams', updated_at=now() where boat_id='qc-reference-c5001' and area_name='Stbd Side Deck' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Kyle Carl Adams', updated_at=now() where boat_id='qc-reference-c5001' and area_name='Port Hull' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Kyle Carl Adams', updated_at=now() where boat_id='qc-reference-c5001' and area_name='Stbd Engine Room' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Imran Majiet', updated_at=now() where boat_id='qc-reference-c5001' and area_name='Flybridge' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Imran Majiet', updated_at=now() where boat_id='qc-reference-c5001' and area_name='Fwd Cockpit & Foredeck' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Moegamat Saleem Philander', updated_at=now() where boat_id='qc-reference-c5001' and area_name='Saloon' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Kyle Carl Adams', updated_at=now() where boat_id='qc-reference-c5001' and area_name='Port Fwd Cabin' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Kyle Carl Adams', updated_at=now() where boat_id='qc-reference-c5001' and area_name='Port Fwd Heads' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Kyle Carl Adams', updated_at=now() where boat_id='qc-reference-c5001' and area_name='Port Aft Cabin' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Kyle Carl Adams', updated_at=now() where boat_id='qc-reference-c5001' and area_name='Port Aft Heads' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Kyle Carl Adams', updated_at=now() where boat_id='qc-reference-c5001' and area_name='Port Passage' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Moegamat Saleem Philander', updated_at=now() where boat_id='qc-reference-c5001' and area_name='Study' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Moegamat Saleem Philander', updated_at=now() where boat_id='qc-reference-c5001' and area_name='Owner''S Heads' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Kyle Carl Adams', updated_at=now() where boat_id='qc-reference-c5002' and area_name='Aft Cockpit' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Kyle Carl Adams', updated_at=now() where boat_id='qc-reference-c5002' and area_name='Fwd Cockpit & Foredeck' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Kyle Carl Adams', updated_at=now() where boat_id='qc-reference-c5002' and area_name='Stbd Side Deck' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Kyle Carl Adams', updated_at=now() where boat_id='qc-reference-c5002' and area_name='Flybridge' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Kyle Carl Adams', updated_at=now() where boat_id='qc-reference-c5002' and area_name='Stbd Hull' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Kyle Carl Adams', updated_at=now() where boat_id='qc-reference-c5002' and area_name='Stbd Engine Room' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Kyle Carl Adams', updated_at=now() where boat_id='qc-reference-c5002' and area_name='Saloon' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Imran Majiet', updated_at=now() where boat_id='qc-reference-c5002' and area_name='Study' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Imtiyaaz Hassan Hoosain', updated_at=now() where boat_id='qc-reference-c5002' and area_name='Port Passage' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Imtiyaaz Hassan Hoosain', updated_at=now() where boat_id='qc-reference-c5002' and area_name='Port Fwd Cabin' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Kyle Carl Adams', updated_at=now() where boat_id='qc-reference-c5003' and area_name='Port Aft Cabin' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Kyle Carl Adams', updated_at=now() where boat_id='qc-reference-c5003' and area_name='Port Passage' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Kyle Carl Adams', updated_at=now() where boat_id='qc-reference-c5003' and area_name='Port Fwd Heads' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Kyle Carl Adams', updated_at=now() where boat_id='qc-reference-c5003' and area_name='Stbd Study & Passage' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Kyle Carl Adams', updated_at=now() where boat_id='qc-reference-c5003' and area_name='Owner''S Heads' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Kyle Carl Adams', updated_at=now() where boat_id='qc-reference-c5003' and area_name='Saloon' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Kyle Carl Adams', updated_at=now() where boat_id='qc-reference-c5003' and area_name='Stbd Engine Room' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Kyle Carl Adams', updated_at=now() where boat_id='qc-reference-c5004' and area_name='Saloon' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Kyle Carl Adams', updated_at=now() where boat_id='qc-reference-c5004' and area_name='Owner''S Heads' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Kyle Carl Adams', updated_at=now() where boat_id='qc-reference-c5004' and area_name='Forepeak' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Kyle Carl Adams', updated_at=now() where boat_id='qc-reference-c5004' and area_name='Port Passage' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Kyle Carl Adams', updated_at=now() where boat_id='qc-reference-c5004' and area_name='Port Aft Heads' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Kyle Carl Adams', updated_at=now() where boat_id='qc-reference-c5004' and area_name='Port Aft Cabin' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Kyle Carl Adams', updated_at=now() where boat_id='qc-reference-c5004' and area_name='Stbd Engine Room' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Kyle Carl Adams', updated_at=now() where boat_id='qc-reference-c5004' and area_name='Port Side Deck' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Kyle Carl Adams', updated_at=now() where boat_id='qc-reference-c5004' and area_name='Port Hull' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Kyle Carl Adams', updated_at=now() where boat_id='qc-reference-c5004' and area_name='Flybridge' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Kyle Carl Adams', updated_at=now() where boat_id='qc-reference-c5005' and area_name='Saloon' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Moegamat Saleem Philander', updated_at=now() where boat_id='qc-reference-c5005' and area_name='Stbd Aft Cabin' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Moegamat Saleem Philander', updated_at=now() where boat_id='qc-reference-c5005' and area_name='Stbd Study & Passage' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Moegamat Saleem Philander', updated_at=now() where boat_id='qc-reference-c5005' and area_name='Owner''S Heads' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Sheldon Barends', updated_at=now() where boat_id='qc-reference-c5005' and area_name='Crew Quarters' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Sheldon Barends', updated_at=now() where boat_id='qc-reference-c5005' and area_name='Flowcoat Inside Bilge Surround' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Sheldon Barends', updated_at=now() where boat_id='qc-reference-c5005' and area_name='Port Aft Cabin' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Kyle Carl Adams', updated_at=now() where boat_id='qc-reference-c5005' and area_name='Aft Cockpit' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Kyle Carl Adams', updated_at=now() where boat_id='qc-reference-c5005' and area_name='Port Engine Room' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Imran Majiet', updated_at=now() where boat_id='qc-reference-c5005' and area_name='Stbd Side Deck' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Imran Majiet', updated_at=now() where boat_id='qc-reference-c5005' and area_name='Flybridge' and coalesce(trim(inspector),'')='';
update public.quality_control_areas set inspector='Sheldon Barends', updated_at=now() where boat_id='qc-reference-c5005' and area_name='Port Hull' and coalesce(trim(inspector),'')='';
commit;
select count(*) as assigned_area_inspectors from public.quality_control_areas where coalesce(trim(inspector),'') <> '';
