-- All QC3 and Handover Quality Control inspector assignments.
-- Safe to rerun: only blank inspector fields are filled.
begin;
with assignments (boat_id, area_name, inspector) as (values
  ('qc-reference-c5005','Saloon','Kyle Carl Adams'),
  ('qc-reference-c5005','Stbd Aft Cabin','Moegamat Saleem Philander'),
  ('qc-reference-c5005','Stbd Study & Passage','Moegamat Saleem Philander'),
  ('qc-reference-c5005','Owner''S Heads','Moegamat Saleem Philander'),
  ('qc-reference-c5005','Crew Quarters','Sheldon Barends'),
  ('qc-reference-c5005','Flowcoat Inside Bilge Surround','Sheldon Barends'),
  ('qc-reference-c5005','Port Aft Cabin','Sheldon Barends'),
  ('qc-reference-c5005','Aft Cockpit','Kyle Carl Adams'),
  ('qc-reference-c5005','Port Engine Room','Kyle Carl Adams'),
  ('qc-reference-c5005','Stbd Side Deck','Imran Majiet'),
  ('qc-reference-c5005','Flybridge','Imran Majiet'),
  ('qc-reference-c5005','Port Hull','Sheldon Barends'),
  ('qc-handover-c5005','Saloon','Kyle Carl Adams'),
  ('qc-handover-c5005','Owner''S Heads','Kyle Carl Adams'),
  ('qc-handover-c5005','Port Fwd Cabin','Kyle Carl Adams'),
  ('qc-handover-c5005','Aft Cockpit','Kyle Carl Adams'),
  ('qc-handover-c5005','Stbd Side Deck','Kyle Carl Adams'),
  ('qc-handover-c5005','Port Hull','Kyle Carl Adams'),
  ('qc-reference-c5004','Saloon','Kyle Carl Adams'),
  ('qc-reference-c5004','Owner''S Heads','Kyle Carl Adams'),
  ('qc-reference-c5004','Forepeak','Kyle Carl Adams'),
  ('qc-reference-c5004','Port Passage','Kyle Carl Adams'),
  ('qc-reference-c5004','Port Aft Heads','Kyle Carl Adams'),
  ('qc-reference-c5004','Port Aft Cabin','Kyle Carl Adams'),
  ('qc-reference-c5004','Stbd Engine Room','Kyle Carl Adams'),
  ('qc-reference-c5004','Port Side Deck','Kyle Carl Adams'),
  ('qc-reference-c5004','Port Hull','Kyle Carl Adams'),
  ('qc-reference-c5004','Flybridge','Kyle Carl Adams'),
  ('qc-handover-c5004','Saloon','Kyle Carl Adams'),
  ('qc-handover-c5004','Stbd Study & Passage','Kyle Carl Adams'),
  ('qc-handover-c5004','Owner''S Heads','Kyle Carl Adams'),
  ('qc-handover-c5004','Port Fwd Heads','Sheldon Barends'),
  ('qc-handover-c5004','Forepeak','Sheldon Barends'),
  ('qc-handover-c5004','Stbd Side Deck','Kyle Carl Adams'),
  ('qc-handover-c5004','Foredeck/Fwd Cockpit','Kyle Carl Adams'),
  ('qc-handover-c5004','Stbd Hull','Kyle Carl Adams'),
  ('qc-reference-c5003','Port Aft Cabin','Kyle Carl Adams'),
  ('qc-reference-c5003','Port Passage','Kyle Carl Adams'),
  ('qc-reference-c5003','Port Fwd Heads','Kyle Carl Adams'),
  ('qc-reference-c5003','Stbd Study & Passage','Kyle Carl Adams'),
  ('qc-reference-c5003','Owner''S Heads','Kyle Carl Adams'),
  ('qc-reference-c5003','Saloon','Kyle Carl Adams'),
  ('qc-reference-c5003','Stbd Engine Room','Kyle Carl Adams'),
  ('qc-handover-c5003','Port Hull','Kyle Carl Adams'),
  ('qc-handover-c5003','Port Engine Room','Kyle Carl Adams'),
  ('qc-handover-c5003','Foredeck/Fwd Cockpit','Kyle Carl Adams'),
  ('qc-handover-c5003','Stbd Aft Cabin','Imran Majiet'),
  ('qc-handover-c5003','Saloon','Kyle Carl Adams'),
  ('qc-reference-c5002','Aft Cockpit','Kyle Carl Adams'),
  ('qc-reference-c5002','Fwd Cockpit & Foredeck','Kyle Carl Adams'),
  ('qc-reference-c5002','Stbd Side Deck','Kyle Carl Adams'),
  ('qc-reference-c5002','Flybridge','Kyle Carl Adams'),
  ('qc-reference-c5002','Stbd Hull','Kyle Carl Adams'),
  ('qc-reference-c5002','Stbd Engine Room','Kyle Carl Adams'),
  ('qc-reference-c5002','Saloon','Kyle Carl Adams'),
  ('qc-reference-c5002','Study','Imran Majiet'),
  ('qc-reference-c5002','Port Passage','Imtiyaaz Hassan Hoosain'),
  ('qc-reference-c5002','Port Fwd Cabin','Imtiyaaz Hassan Hoosain'),
  ('qc-handover-c5002','Stbd Heads','Kyle Carl Adams'),
  ('qc-handover-c5002','Port Fwd Heads','Kyle Carl Adams'),
  ('qc-handover-c5002','Port Passage','Kyle Carl Adams'),
  ('qc-handover-c5002','Saloon','Kyle Carl Adams'),
  ('qc-handover-c5002','Foredeck/Fwd Cockpit','Kyle Carl Adams'),
  ('qc-handover-c5002','Port Engine Room','Kyle Carl Adams'),
  ('qc-handover-c5002','Stbd Side Deck','Kyle Carl Adams'),
  ('qc-reference-c5001','Port Side Deck','Kyle Carl Adams'),
  ('qc-reference-c5001','Stbd Side Deck','Kyle Carl Adams'),
  ('qc-reference-c5001','Port Hull','Kyle Carl Adams'),
  ('qc-reference-c5001','Stbd Engine Room','Kyle Carl Adams'),
  ('qc-reference-c5001','Flybridge','Imran Majiet'),
  ('qc-reference-c5001','Fwd Cockpit & Foredeck','Imran Majiet'),
  ('qc-reference-c5001','Saloon','Moegamat Saleem Philander'),
  ('qc-reference-c5001','Port Fwd Cabin','Kyle Carl Adams'),
  ('qc-reference-c5001','Port Fwd Heads','Kyle Carl Adams'),
  ('qc-reference-c5001','Port Aft Cabin','Kyle Carl Adams'),
  ('qc-reference-c5001','Port Aft Heads','Kyle Carl Adams'),
  ('qc-reference-c5001','Port Passage','Kyle Carl Adams'),
  ('qc-reference-c5001','Study','Moegamat Saleem Philander'),
  ('qc-reference-c5001','Owner''S Heads','Moegamat Saleem Philander'),
  ('qc-handover-c5001','Saloon','Kyle Carl Adams'),
  ('qc-handover-c5001','Port Aft Heads','Kyle Carl Adams'),
  ('qc-handover-c5001','Port Fwd Cabin','Kyle Carl Adams'),
  ('qc-handover-c5001','Owner''S Heads','Kyle Carl Adams'),
  ('qc-handover-c5001','Foredeck/Fwd Cockpit','Kyle Carl Adams'),
  ('qc-handover-c5001','Port Side Deck','Kyle Carl Adams'),
  ('qc-reference-c2026','Port Hull','Sheldon Barends'),
  ('qc-reference-c2026','Saloon','Kyle Carl Adams'),
  ('qc-reference-c2026','Aft Cockpit','Kyle Carl Adams'),
  ('qc-reference-c2026','Port Engine Room','Kyle Carl Adams'),
  ('qc-reference-c2026','Stbd Fwd Cabin','Kyle Carl Adams'),
  ('qc-reference-c2026','Stbd Passage','Kyle Carl Adams'),
  ('qc-reference-c2026','Owner''S Heads','Kyle Carl Adams'),
  ('qc-handover-c2026','Stbd Passage','Imran Majiet'),
  ('qc-handover-c2026','Stbd Aft Cabin','Imran Majiet'),
  ('qc-handover-c2026','Saloon','Imran Majiet'),
  ('qc-handover-c2026','Aft Cockpit','Imran Majiet'),
  ('qc-handover-c2026','Stbd Hull','Moegamat Saleem Philander'),
  ('qc-reference-c2025','Saloon','Sheldon Barends'),
  ('qc-reference-c2025','Port Aft Heads','Sheldon Barends'),
  ('qc-reference-c2025','Crew Quarters','Sheldon Barends'),
  ('qc-reference-c2025','Fwd Cockpit & Foredeck','Sheldon Barends'),
  ('qc-reference-c2025','Aft Cockpit','Sheldon Barends'),
  ('qc-reference-c2025','Port Engine Room','Sheldon Barends'),
  ('qc-reference-c2025','Port Hull','Sheldon Barends'),
  ('qc-reference-c2025','Stbd Fwd Heads','Sheldon Barends'),
  ('qc-reference-c2025','Stbd Fwd Cabin','Sheldon Barends'),
  ('qc-reference-c2025','Stbd Passage','Sheldon Barends'),
  ('qc-reference-c2025','Stbd Aft Heads','Sheldon Barends'),
  ('qc-reference-c2025','Stbd Aft Cabin','Sheldon Barends'),
  ('qc-handover-c2025','Stbd Passage','Sheldon Barends'),
  ('qc-handover-c2025','Stbd Aft Cabin','Sheldon Barends'),
  ('qc-handover-c2025','Port Fwd Passage','Sheldon Barends'),
  ('qc-handover-c2025','Port Mid Heads','Sheldon Barends'),
  ('qc-handover-c2025','Port Aft Cabin','Sheldon Barends'),
  ('qc-handover-c2025','Fwd Cockpit & Foredeck','Sheldon Barends'),
  ('qc-handover-c2025','Stbd Hull','Sheldon Barends'),
  ('qc-handover-c2025','Aft Cockpit','Sheldon Barends'),
  ('qc-reference-c2024','Saloon','Kyle Carl Adams'),
  ('qc-reference-c2024','Stbd Fwd Heads','Sheldon Barends'),
  ('qc-reference-c2024','Stbd Passage','Sheldon Barends'),
  ('qc-reference-c2024','Owner''S Heads','Kyle Carl Adams'),
  ('qc-reference-c2024','Stbd Study & Passage','Kyle Carl Adams'),
  ('qc-reference-c2024','Stbd Aft Cabin','Kyle Carl Adams'),
  ('qc-reference-c2024','Aft Cockpit','Imran Majiet'),
  ('qc-reference-c2024','Flybridge','Imran Majiet'),
  ('qc-reference-c2024','Port Engine Room','Imran Majiet'),
  ('qc-reference-c2024','Stbd Hull','Kyle Carl Adams'),
  ('qc-reference-c2024','Port Hull','Kyle Carl Adams'),
  ('qc-handover-c2024','Port Mid Cabin','Sheldon Barends'),
  ('qc-handover-c2024','Port Aft Heads','Sheldon Barends'),
  ('qc-handover-c2024','Port Side Deck','Sheldon Barends'),
  ('qc-handover-c2024','Forepeak','Sheldon Barends'),
  ('qc-reference-c2023','Saloon','Imran Majiet'),
  ('qc-reference-c2023','Stbd Fwd Heads','Sheldon Barends'),
  ('qc-reference-c2023','Stbd Fwd Cabin','Sheldon Barends'),
  ('qc-reference-c2023','Stbd Passage','Sheldon Barends'),
  ('qc-reference-c2023','Stbd Aft Heads','Sheldon Barends'),
  ('qc-reference-c2023','Stbd Aft Cabin','Sheldon Barends'),
  ('qc-reference-c2023','Forepeak','Sheldon Barends'),
  ('qc-reference-c2023','Port Aft Heads','Kyle Carl Adams'),
  ('qc-reference-c2023','Port Aft Cabin','Kyle Carl Adams'),
  ('qc-reference-c2023','Port Passage','Kyle Carl Adams'),
  ('qc-reference-c2023','Port Fwd Cabin','Kyle Carl Adams'),
  ('qc-reference-c2023','Port Fwd Heads','Kyle Carl Adams'),
  ('qc-reference-c2023','Stbd Hull','Sheldon Barends'),
  ('qc-reference-c2023','Port Hull','Kyle Carl Adams'),
  ('qc-reference-c2023','Flybridge','Imran Majiet'),
  ('qc-reference-c2023','Stbd Engine Room','Imran Majiet'),
  ('qc-reference-c2023','Stbd Side Deck','Sheldon Barends'),
  ('qc-reference-c2023','Port Side Deck','Sheldon Barends'),
  ('qc-reference-c2023','Fwd Cockpit & Foredeck','Sheldon Barends'),
  ('qc-handover-c2023','Port Passage','Sheldon Barends'),
  ('qc-handover-c2023','Contractor','Sheldon Barends'),
  ('qc-handover-c2023','Stbd Passage','Sheldon Barends'),
  ('qc-handover-c2023','Stbd Aft Cabin','Sheldon Barends'),
  ('qc-handover-c2023','Saloon','Sheldon Barends'),
  ('qc-handover-c2023','Aft Cockpit','Sheldon Barends'),
  ('qc-handover-c2023','Forward Cockpit','Sheldon Barends'),
  ('qc-handover-c2023','Flybridge','Sheldon Barends'),
  ('qc-handover-c2023','Port Hull','Sheldon Barends'),
  ('qc-reference-c2022','Saloon','Kyle Carl Adams'),
  ('qc-reference-c2022','Stbd Fwd Heads','Mogamat Yunis Jabaar'),
  ('qc-reference-c2022','Stbd Passage','Mogamat Yunis Jabaar'),
  ('qc-reference-c2022','Owner''S Heads','Imran Majiet'),
  ('qc-reference-c2022','Study','Imran Majiet'),
  ('qc-reference-c2022','Stbd Aft Cabin','Imran Majiet'),
  ('qc-reference-c2022','Port Fwd Heads','Imtiyaaz Hassan Hoosain'),
  ('qc-reference-c2022','Port Mid Cabin','Imtiyaaz Hassan Hoosain'),
  ('qc-reference-c2022','Port Mid Heads','Imtiyaaz Hassan Hoosain'),
  ('qc-reference-c2022','Port Aft Cabin','Kyle Carl Adams'),
  ('qc-reference-c2022','Aft Cockpit','Imran Majiet'),
  ('qc-reference-c2022','Stbd Engine Room','Imran Majiet'),
  ('qc-reference-c2022','Flybridge','Imtiyaaz Hassan Hoosain'),
  ('qc-reference-c2022','Fwd Cockpit & Foredeck','Mogamat Yunis Jabaar'),
  ('qc-reference-c2022','Crew Quarters','Kyle Carl Adams'),
  ('qc-reference-c2022','Port Hull','Kyle Carl Adams'),
  ('qc-reference-c2022','Stbd Hull','Kyle Carl Adams'),
  ('qc-handover-c2022','Port Fwd Cabin','Sheldon Barends'),
  ('qc-handover-c2022','Port Mid Cabin','Sheldon Barends'),
  ('qc-handover-c2022','Port Aft Cabin','Sheldon Barends'),
  ('qc-handover-c2022','Flybridge','Sheldon Barends'),
  ('qc-reference-c1076','Saloon','Imtiyaaz Hassan Hoosain'),
  ('qc-reference-c1076','Study','Imtiyaaz Hassan Hoosain'),
  ('qc-reference-c1076','Stbd Aft Heads','Imtiyaaz Hassan Hoosain'),
  ('qc-reference-c1076','Aft Cockpit','Imtiyaaz Hassan Hoosain'),
  ('qc-reference-c1076','Port Engine Room','Imtiyaaz Hassan Hoosain'),
  ('qc-reference-c1076','Stbd Side Deck','Mogamat Yunis Jabaar'),
  ('qc-reference-c1076','Fwd Cockpit & Foredeck','Mogamat Yunis Jabaar'),
  ('qc-reference-c1075','Stbd Aft Cabin','Imtiyaaz Hassan Hoosain'),
  ('qc-reference-c1075','Study','Imtiyaaz Hassan Hoosain'),
  ('qc-reference-c1075','Owner''S Heads','Imtiyaaz Hassan Hoosain'),
  ('qc-reference-c1075','Stbd Passage','Imtiyaaz Hassan Hoosain'),
  ('qc-reference-c1075','Stbd Fwd Cabin','Imtiyaaz Hassan Hoosain'),
  ('qc-reference-c1075','Stbd Fwd Heads','Imtiyaaz Hassan Hoosain'),
  ('qc-reference-c1075','Aft Cockpit','Mogamat Yunis Jabaar'),
  ('qc-reference-c1075','Stbd Engine Room','Mogamat Yunis Jabaar'),
  ('qc-reference-c1075','Fwd Cockpit & Foredeck','Imtiyaaz Hassan Hoosain'),
  ('qc-reference-c1075','Stbd Side Deck','Imtiyaaz Hassan Hoosain'),
  ('qc-reference-c1075','Flybridge','Imtiyaaz Hassan Hoosain'),
  ('qc-reference-c1075','Port Hull','Imtiyaaz Hassan Hoosain'),
  ('qc-reference-c1074','Saloon','Imtiyaaz Hassan Hoosain'),
  ('qc-reference-c1074','Study','Imtiyaaz Hassan Hoosain'),
  ('qc-reference-c1074','Owner''S Heads','Imtiyaaz Hassan Hoosain'),
  ('qc-reference-c1074','Stbd Fwd Cabin','Imtiyaaz Hassan Hoosain'),
  ('qc-reference-c1074','Stbd Fwd Heads','Imtiyaaz Hassan Hoosain'),
  ('qc-reference-c1074','Port Aft Cabin','Mogamat Yunis Jabaar'),
  ('qc-reference-c1074','Port Aft Heads','Mogamat Yunis Jabaar'),
  ('qc-reference-c1074','Port Passage','Mogamat Yunis Jabaar'),
  ('qc-reference-c1074','Port Fwd Heads','Mogamat Yunis Jabaar'),
  ('qc-reference-c1074','Port Fwd Cabin','Mogamat Yunis Jabaar'),
  ('qc-reference-c1074','Aft Cockpit','Imtiyaaz Hassan Hoosain'),
  ('qc-reference-c1074','Stbd Engine Room','Imtiyaaz Hassan Hoosain'),
  ('qc-reference-c1074','Port Side Deck','Mogamat Yunis Jabaar'),
  ('qc-reference-c1074','Fwd Cockpit & Foredeck','Mogamat Yunis Jabaar'),
  ('qc-reference-c1074','Flybridge','Mogamat Yunis Jabaar'),
  ('qc-reference-c1074','Stbd Hull','Mogamat Yunis Jabaar'),
  ('qc-reference-c1074','A/S','Imtiyaaz Hassan Hoosain'),
  ('qc-reference-c1074','Port Hull','Imtiyaaz Hassan Hoosain'),
  ('qc-reference-c1073','Saloon','Imtiyaaz Hassan Hoosain'),
  ('qc-reference-c1073','Stbd Fwd Cabin','Imtiyaaz Hassan Hoosain'),
  ('qc-reference-c1073','Stbd Fwd Heads','Imtiyaaz Hassan Hoosain'),
  ('qc-reference-c1073','Owner''S Heads','Mogamat Yunis Jabaar'),
  ('qc-reference-c1073','Stbd Study & Passage','Mogamat Yunis Jabaar'),
  ('qc-reference-c1073','Stbd Aft Cabin','Mogamat Yunis Jabaar'),
  ('qc-reference-c1073','Port Aft Cabin','Mogamat Yunis Jabaar'),
  ('qc-reference-c1073','Port Aft Heads','Mogamat Yunis Jabaar'),
  ('qc-reference-c1073','Port Passage','Mogamat Yunis Jabaar'),
  ('qc-reference-c1073','Port Fwd Heads','Mogamat Yunis Jabaar'),
  ('qc-reference-c1073','Port Fwd Cabin','Mogamat Yunis Jabaar'),
  ('qc-reference-c1073','Aft Cockpit','Imtiyaaz Hassan Hoosain'),
  ('qc-reference-c1073','Port Engine Room','Imtiyaaz Hassan Hoosain'),
  ('qc-reference-c1073','Port Side Deck','Mogamat Yunis Jabaar'),
  ('qc-reference-c1073','Flybridge','Mogamat Yunis Jabaar'),
  ('qc-reference-c1073','Fwd Cockpit & Foredeck','Mogamat Yunis Jabaar'),
  ('qc-reference-c1073','Port Hull','Mogamat Yunis Jabaar'),
  ('qc-reference-c1073','Stbd Hull','Imtiyaaz Hassan Hoosain'),
  ('qc-handover-c1072','Stbd Fwd Heads','Zunaid Hoosen'),
  ('qc-handover-c1072','Stbd Passage','Zunaid Hoosen'),
  ('qc-handover-c1072','Study','Zunaid Hoosen'),
  ('qc-handover-c1072','Stbd Aft Cabin','Zunaid Hoosen'),
  ('qc-handover-c1072','Aft Cockpit','Zunaid Hoosen'),
  ('qc-handover-c1072','Stb Deck','Zunaid Hoosen'),
  ('qc-handover-c1072','Flybribge','Zunaid Hoosen'),
  ('qc-handover-c1072','Stbd Hull','Zunaid Hoosen'),
  ('qc-handover-c1072','Port Fwd Heads','Imtiyaaz Hassan Hoosain'),
  ('qc-handover-c1072','Port Aft Heads','Imtiyaaz Hassan Hoosain'),
  ('qc-handover-c1072','Port Aft Cabin','Imtiyaaz Hassan Hoosain'),
  ('qc-reference-c1071','Saloon','Mogamat Yunis Jabaar'),
  ('qc-reference-c1071','Port Aft Cabin','Mogamat Yunis Jabaar'),
  ('qc-reference-c1071','Port Aft Heads','Mogamat Yunis Jabaar'),
  ('qc-reference-c1071','Port Passage','Mogamat Yunis Jabaar'),
  ('qc-reference-c1071','Port Fwd Cabin','Imtiyaaz Hassan Hoosain'),
  ('qc-reference-c1071','Port Fwd Heads','Imtiyaaz Hassan Hoosain'),
  ('qc-reference-c1071','Study','Imtiyaaz Hassan Hoosain'),
  ('qc-reference-c1071','Stbd Fwd Cabin','Imtiyaaz Hassan Hoosain'),
  ('qc-reference-c1071','Stbd Fwd Heads','Imtiyaaz Hassan Hoosain'),
  ('qc-reference-c1071','Aft Cockpit','Mogamat Yunis Jabaar'),
  ('qc-reference-c1071','Port Engine Room','Mogamat Yunis Jabaar'),
  ('qc-reference-c1071','Fwd Cockpit & Foredeck','Imtiyaaz Hassan Hoosain'),
  ('qc-reference-c1071','Flybridge','Imtiyaaz Hassan Hoosain'),
  ('qc-reference-c1071','Port Hull','Mogamat Yunis Jabaar'),
  ('qc-reference-c1071','Stbd Hull','Imtiyaaz Hassan Hoosain'),
  ('qc-handover-c1071','Stb Deck','Zunaid Hoosen'),
  ('qc-handover-c1071','Flybridge','Zunaid Hoosen'),
  ('qc-handover-c1071','Stbd Hull','Zunaid Hoosen'),
  ('qc-handover-c1071','Aft Cockpit','Zunaid Hoosen'),
  ('qc-handover-c1071','Saloon','Zunaid Hoosen'),
  ('qc-handover-c1071','Port Passage','Riyaaz Harold'),
  ('qc-handover-c1071','Port Aft Cabin','Riyaaz Harold'),
  ('qc-handover-c1071','Stbd Fwd Cabin','Zunaid Hoosen'),
  ('qc-handover-c1071','Stbd Passage','Zunaid Hoosen'),
  ('qc-handover-c1071','Study','Zunaid Hoosen'),
  ('qc-handover-c1070','Saloon','Zunaid Hoosen'),
  ('qc-handover-c1070','Stbd Fwd Cabin','Zunaid Hoosen'),
  ('qc-handover-c1070','Stbd Passage','Zunaid Hoosen'),
  ('qc-handover-c1070','Study','Zunaid Hoosen'),
  ('qc-handover-c1070','Stbd Aft Cabin','Zunaid Hoosen'),
  ('qc-handover-c1070','Port Fwd Heads','Zunaid Hoosen'),
  ('qc-handover-c1070','Port Aft Cabin','Zunaid Hoosen'),
  ('qc-handover-c1070','Aft Cockpit','Zunaid Hoosen'),
  ('qc-handover-c1070','Port Hull','Zunaid Hoosen'),
  ('qc-handover-c1070','Flybrige','Zunaid Hoosen'),
  ('qc-handover-c1069','Saloon','Zunaid Hoosen'),
  ('qc-handover-c1069','Stbd Passage','Zunaid Hoosen'),
  ('qc-handover-c1069','Study','Zunaid Hoosen'),
  ('qc-handover-c1069','Stbd Aft Cabin','Zunaid Hoosen'),
  ('qc-handover-c1069','Port Fwd Heads','Kyle Carl Adams'),
  ('qc-handover-c1069','Port Passage','Imtiyaaz Hassan Hoosain'),
  ('qc-handover-c1069','Aft Cockpit','Zunaid Hoosen'),
  ('qc-handover-c1069','Flybridge','Zunaid Hoosen'),
  ('qc-handover-c1069','Stbd Hull','Zunaid Hoosen'),
  ('qc-handover-c1068','Port Passage','Imtiyaaz Hassan Hoosain'),
  ('qc-handover-c1068','Port Fwd Heads','Imtiyaaz Hassan Hoosain'),
  ('qc-handover-c1068','Stbd Fwd Heads','Imtiyaaz Hassan Hoosain'),
  ('qc-reference-b9078','Saloon','Jodi Jackson'),
  ('qc-reference-b9078','Owner''S Heads','Jodi Jackson'),
  ('qc-reference-b9078','Port Fwd Cabin','Jodi Jackson'),
  ('qc-reference-b9078','Aft Cockpit','Jodi Jackson'),
  ('qc-reference-b9078','Fwd Cockpit & Foredeck','Jodi Jackson'),
  ('qc-reference-b9078','Flybridge','Jodi Jackson'),
  ('qc-reference-b9078','Port Hull','Jodi Jackson'),
  ('qc-handover-b9078','Flybridge','Imran Majiet'),
  ('qc-handover-b9078','Stbd Hull','Imran Majiet'),
  ('qc-handover-b9078','Port Aft Cabin','Moegamat Saleem Philander'),
  ('qc-handover-b9078','Stbd Aft Cabin','Moegamat Saleem Philander'),
  ('qc-reference-b9077','Saloon','Jodi Jackson'),
  ('qc-reference-b9077','Port Heads','Mogamat Yunis Jabaar'),
  ('qc-reference-b9077','Port Aft Cabin','Mogamat Yunis Jabaar'),
  ('qc-reference-b9077','Owner''S Heads','Imtiyaaz Hassan Hoosain'),
  ('qc-reference-b9077','Aft Cockpit','Jodi Jackson'),
  ('qc-reference-b9077','Fwd Cockpit & Foredeck','Jodi Jackson'),
  ('qc-reference-b9077','Flybridge','Jodi Jackson'),
  ('qc-reference-b9077','Port Engine Room','Jodi Jackson'),
  ('qc-reference-b9077','Port Hull','Jodi Jackson'),
  ('qc-handover-b9077','Port Passage','Sheldon Barends'),
  ('qc-handover-b9077','Port Aft Cabin','Sheldon Barends'),
  ('qc-handover-b9077','Stbd Owner''S Cabin','Sheldon Barends'),
  ('qc-handover-b9077','Saloon','Sheldon Barends'),
  ('qc-handover-b9077','Aft Cockpit','Sheldon Barends'),
  ('qc-handover-b9077','Port Hull','Sheldon Barends'),
  ('qc-reference-b9076','Saloon','Imtiyaaz Hassan Hoosain'),
  ('qc-reference-b9076','Port Passage','Mogamat Yunis Jabaar'),
  ('qc-reference-b9076','Port Fwd Cabin','Mogamat Yunis Jabaar'),
  ('qc-reference-b9076','Stbd Aft Cabin','Mogamat Yunis Jabaar'),
  ('qc-reference-b9076','Stbd Engine Room','Imtiyaaz Hassan Hoosain'),
  ('qc-reference-b9076','Port Side Deck','Mogamat Yunis Jabaar'),
  ('qc-reference-b9076','Flybridge','Mogamat Yunis Jabaar'),
  ('qc-reference-b9076','Port Hull','Jodi Jackson'),
  ('qc-handover-b9076','Saloon','Sheldon Barends'),
  ('qc-handover-b9076','Stbd Study & Passage','Sheldon Barends'),
  ('qc-handover-b9076','Aft Cockpit','Sheldon Barends'),
  ('qc-handover-b9076','Port Hull','Sheldon Barends'),
  ('qc-handover-b9076','Flybridge','Sheldon Barends'),
  ('qc-handover-b9076','Port Passage','Zunaid Hoosen'),
  ('qc-handover-b9076','Port Aft Cabin','Zunaid Hoosen'),
  ('qc-reference-b9075','Saloon','Imtiyaaz Hassan Hoosain'),
  ('qc-reference-b9075','Stbd Study & Passage','Kyle Carl Adams'),
  ('qc-reference-b9075','Owner''S Heads','Kyle Carl Adams'),
  ('qc-reference-b9075','Port Heads','Imran Majiet'),
  ('qc-reference-b9075','Port Aft Cabin','Imran Majiet'),
  ('qc-reference-b9075','Stbd Engine Room','Imtiyaaz Hassan Hoosain'),
  ('qc-reference-b9075','Flybridge','Imran Majiet'),
  ('qc-reference-b9075','Fwd Cockpit & Foredeck','Imran Majiet'),
  ('qc-reference-b9075','Stbd Hull','Imtiyaaz Hassan Hoosain'),
  ('qc-handover-b9075','Saloon','Zunaid Hoosen'),
  ('qc-handover-b9075','Aftcockpit','Zunaid Hoosen'),
  ('qc-handover-b9075','Stbd Aft Cabin','Imran Majiet'),
  ('qc-reference-b9074','Saloon','Imtiyaaz Hassan Hoosain'),
  ('qc-reference-b9074','Stb Heads','Imtiyaaz Hassan Hoosain'),
  ('qc-reference-b9074','Port Heads','Imran Majiet'),
  ('qc-reference-b9074','Stbd Engine Room','Imtiyaaz Hassan Hoosain'),
  ('qc-reference-b9074','Fwd Cockpit & Foredeck','Imran Majiet'),
  ('qc-reference-b9074','Stbd Side Deck','Imran Majiet'),
  ('qc-reference-b9074','Port Hull','Imtiyaaz Hassan Hoosain'),
  ('qc-handover-b9074','Stbd Aft Cabin','Moegamat Saleem Philander'),
  ('qc-handover-b9074','Flybridge','Moegamat Saleem Philander'),
  ('qc-handover-b9074','Stbd Hull','Moegamat Saleem Philander'),
  ('qc-handover-b9074','Port Fwd Heads','Zunaid Hoosen'),
  ('qc-handover-b9074','Port Fwd Cabin','Zunaid Hoosen'),
  ('qc-handover-b9074','Stb Deck','Zunaid Hoosen'),
  ('qc-reference-b8130','Saloon','Jodi Jackson'),
  ('qc-reference-b8130','Port Passage','Jodi Jackson'),
  ('qc-reference-b8130','Port Fwd Heads','Jodi Jackson'),
  ('qc-reference-b8130','Stbd Aft Cabin','Riyaaz Harold'),
  ('qc-reference-b8130','Port Engine Room','Jodi Jackson'),
  ('qc-reference-b8130','Fwd Cockpit & Foredeck','Riyaaz Harold'),
  ('qc-reference-b8130','Port Hull','Jodi Jackson'),
  ('qc-reference-b8130','Flybridge','Moegamat Saleem Philander'),
  ('qc-handover-b8130','Port Hull','Sheldon Barends'),
  ('qc-handover-b8130','Stbd Side Deck','Sheldon Barends'),
  ('qc-handover-b8130','Flybridge','Sheldon Barends'),
  ('qc-handover-b8130','Saloon','Sheldon Barends'),
  ('qc-handover-b8130','Port Passage','Sheldon Barends'),
  ('qc-handover-b8130','Port Aft Cabin','Sheldon Barends'),
  ('qc-handover-b8130','Stbd Aft Cabin','Sheldon Barends'),
  ('qc-reference-b8129','Saloon','Jodi Jackson'),
  ('qc-reference-b8129','Port Fwd Heads','Jodi Jackson'),
  ('qc-reference-b8129','Owner''S Heads','Jodi Jackson'),
  ('qc-reference-b8129','Aft Cockpit','Jodi Jackson'),
  ('qc-reference-b8129','Fwd Cockpit & Foredeck','Mogamat Yunis Jabaar'),
  ('qc-reference-b8129','Port Hull','Jodi Jackson'),
  ('qc-reference-b8129','Stbd Engine Room','Jodi Jackson'),
  ('qc-reference-b8129','Stbd Hull','Jodi Jackson'),
  ('qc-handover-b8129','Aft Cockpit','Sheldon Barends'),
  ('qc-handover-b8129','Saloon','Sheldon Barends'),
  ('qc-handover-b8129','Stbd Study & Passage','Sheldon Barends'),
  ('qc-handover-b8129','Port Passage','Sheldon Barends'),
  ('qc-handover-b8129','Port Aft Heads','Sheldon Barends'),
  ('qc-handover-b8129','Stbd Side Deck','Imran Majiet'),
  ('qc-handover-b8129','Port Hull','Imran Majiet'),
  ('qc-reference-b8128','Saloon','Jodi Jackson'),
  ('qc-reference-b8128','Owner''S Heads','Jodi Jackson'),
  ('qc-reference-b8128','Port Aft Heads','Jodi Jackson'),
  ('qc-reference-b8128','Port Engine Room','Jodi Jackson'),
  ('qc-reference-b8128','Flybridge','Jodi Jackson'),
  ('qc-reference-b8128','Stbd Hull','Jodi Jackson'),
  ('qc-reference-b8127','Saloon','Jodi Jackson'),
  ('qc-reference-b8127','Port Fwd Heads','Jodi Jackson'),
  ('qc-reference-b8127','Stbd Fwd Heads','Jodi Jackson'),
  ('qc-reference-b8127','Aft Cockpit','Jodi Jackson'),
  ('qc-reference-b8127','Port Engine Room','Jodi Jackson'),
  ('qc-reference-b8127','Fwd Cockpit & Foredeck','Jodi Jackson'),
  ('qc-reference-b8127','Flybridge','Jodi Jackson'),
  ('qc-handover-b8127','Stbd Hull','Sheldon Barends'),
  ('qc-handover-b8127','Forward Cockpit','Sheldon Barends'),
  ('qc-handover-b8127','Stbd Fwd Cabin','Sheldon Barends'),
  ('qc-handover-b8127','Port Fwd Cabin','Sheldon Barends'),
  ('qc-handover-b8127','Port Hull','Sheldon Barends'),
  ('qc-reference-b8126','Saloon','Jodi Jackson'),
  ('qc-reference-b8126','Port Passage','Jodi Jackson'),
  ('qc-reference-b8126','Port Fwd Heads','Jodi Jackson'),
  ('qc-reference-b8126','Stbd Aft Heads','Mogamat Yunis Jabaar'),
  ('qc-reference-b8126','Stbd Fwd Cabin','Mogamat Yunis Jabaar'),
  ('qc-reference-b8126','Aft Cockpit','Jodi Jackson'),
  ('qc-reference-b8126','Stbd Engine Room','Jodi Jackson'),
  ('qc-reference-b8126','Fwd Cockpit & Foredeck','Mogamat Yunis Jabaar'),
  ('qc-reference-b8126','Flybridge','Jodi Jackson'),
  ('qc-reference-b8126','Port Hull','Jodi Jackson'),
  ('qc-handover-b8126','Saloon','Moegamat Saleem Philander'),
  ('qc-handover-b8126','Stb Pessage','Moegamat Saleem Philander'),
  ('qc-handover-b8126','Stbd Aft Cabin','Moegamat Saleem Philander'),
  ('qc-handover-b8126','Port Aft Cabin','Moegamat Saleem Philander'),
  ('qc-handover-b8126','Aft Cockpit','Imran Majiet'),
  ('qc-handover-b8126','Flybridge','Zunaid Hoosen'),
  ('qc-handover-b8126','Fwd Cockpit & Foredeck','Zunaid Hoosen'),
  ('qc-handover-b8126','Stb Deck','Zunaid Hoosen'),
  ('qc-handover-b8126','Port Deck','Zunaid Hoosen')
)
update public.quality_control_areas as area
set inspector=assignments.inspector, updated_at=now()
from assignments
where area.boat_id=assignments.boat_id
  and area.area_name=assignments.area_name
  and coalesce(trim(area.inspector),'')='';
commit;
select count(*) as assigned_area_inspectors from public.quality_control_areas where coalesce(trim(inspector),'') <> '';
