-- Run supabase/migrations/20260901_enforce_unique_stock_codes.sql first.
-- Imports only complete records and safely skips any stock code already present.

begin;

insert into public.stock_categories (name) values
  ('Deck Hardware and Fittings'),
  ('Electrical'),
  ('Joinery and Interior'),
  ('Loose items/Skipper''s pack'),
  ('Mechanical'),
  ('Miscellaneous'),
  ('Plumbing'),
  ('Safety')
on conflict (name) do nothing;

with incoming(category_name, description, stock_code) as (
  values
    ('Deck Hardware and Fittings', '6 inch inspect port', 'INSPRT SW17560'),
    ('Deck Hardware and Fittings', 'Aft cockpit fridge vent', 'LVRE WM282387'),
    ('Deck Hardware and Fittings', 'Aft cockpit shades', 'CKPT ASC B8C HG'),
    ('Deck Hardware and Fittings', 'Aft cockpit teflon winch panel inspection', 'JC-26797'),
    ('Deck Hardware and Fittings', 'Anchor bridal srtop', 'ANCHR BRDL STRP'),
    ('Deck Hardware and Fittings', 'Anchor chain rope strop', 'ANCHR STRP'),
    ('Deck Hardware and Fittings', 'anchor locker telfon strips', 'JA-30771'),
    ('Deck Hardware and Fittings', 'B3 comp door s/s capping', '21000348'),
    ('Deck Hardware and Fittings', 'B8 Gas strut', 'GSLFT 875-12'),
    ('Deck Hardware and Fittings', 'Black Fenders', 'FNDR A0453BKS'),
    ('Deck Hardware and Fittings', 'Block 60mm Fiddle', 'BLK LW29196031'),
    ('Deck Hardware and Fittings', 'BLOCK Single+Becket', 'BLK LW29196004'),
    ('Deck Hardware and Fittings', 'Cockpit seat/LAZERETTE catches', 'HTCH LK STR PLN'),
    ('Deck Hardware and Fittings', 'Companionway Door Lock', 'LKSO MM0110350'),
    ('Deck Hardware and Fittings', 'Cushion codes (BEGINNING) OLD CUSHIONS', 'TD B8 RC04'),
    ('Deck Hardware and Fittings', 'Cushion Popper Femal', 'PLNGRFP 0507475-1'),
    ('Deck Hardware and Fittings', 'Cushion Popper Male', 'PLNGRMP 0107426B'),
    ('Deck Hardware and Fittings', 'CWD', 'DRCMPNWY ASBB83'),
    ('Deck Hardware and Fittings', 'DAVIT FRAME', '20311007/2'),
    ('Deck Hardware and Fittings', 'DAVIT hinge bolts', 'BTH16X60S'),
    ('Deck Hardware and Fittings', 'davit hinge penny washer', 'WSP16S'),
    ('Deck Hardware and Fittings', 'Davit Rubber Stopper', 'DR STP WH8402'),
    ('Deck Hardware and Fittings', 'DAVIT WINCH+ROPE', 'WNCH WN 101020'),
    ('Deck Hardware and Fittings', 'Davitt shackle', 'SHCKL HA 2108'),
    ('Deck Hardware and Fittings', 'Davitt single block', 'BLK HA304NP'),
    ('Deck Hardware and Fittings', 'Deck fillercap', 'DCK FLL'),
    ('Deck Hardware and Fittings', 'Deck wash addaptor', 'WSHDWN ADPTR'),
    ('Deck Hardware and Fittings', 'Deckwash fitting', 'WSHDWN QC'),
    ('Deck Hardware and Fittings', 'Diesel Filler Cap', 'DCK FLL AM DSLG'),
    ('Deck Hardware and Fittings', 'ELECT GRILL CORIAN TOP', 'STRN C1 MM ADEBG'),
    ('Deck Hardware and Fittings', 'engine room butt hinges', '21000873'),
    ('Deck Hardware and Fittings', 'Engine room lid , fwd locker hinges', '21000482'),
    ('Deck Hardware and Fittings', 'Flush mount magnet Big', 'CTCH 0207665N'),
    ('Deck Hardware and Fittings', 'Flush mount magnet Medium', 'CTCH 0207663N'),
    ('Deck Hardware and Fittings', 'Flush mount magnet Small', '0207671P'),
    ('Deck Hardware and Fittings', 'Fly bridge aft shades', 'FBRNCLS B8 AMS'),
    ('Deck Hardware and Fittings', 'Flybridge Enclosure', 'FBRNCLS B8'),
    ('Deck Hardware and Fittings', 'flybridge track for shade', 'TRK BBG530/4.8'),
    ('Deck Hardware and Fittings', 'flyrbridge lid teflon rope cover strip', 'JC-26790'),
    ('Deck Hardware and Fittings', 'Footman loops', 'FTMNLP 25'),
    ('Deck Hardware and Fittings', 'foredeck locker hinge backing plate', '21000374'),
    ('Deck Hardware and Fittings', 'foredeck perco latch', 'SO M1-25-31-78'),
    ('Deck Hardware and Fittings', 'FUSION remote - exterior', 'FU MSERX400'),
    ('Deck Hardware and Fittings', 'fwd cockpit cup holder', '21000858'),
    ('Deck Hardware and Fittings', 'fwd cockpit door', 'CKPT DR B1F'),
    ('Deck Hardware and Fittings', 'fwd cockpit door frame', '21000898'),
    ('Deck Hardware and Fittings', 'FWD cockpit metal studs', 'CAF316 230110'),
    ('Deck Hardware and Fittings', 'Galv Shackle Big', 'SHCKL GB'),
    ('Deck Hardware and Fittings', 'GAS GRILL CORIAN TOP', 'STRN C1 MM ADGBG'),
    ('Deck Hardware and Fittings', 'gas strut end fitting + split pin', 'GSLFT EFSS13M'),
    ('Deck Hardware and Fittings', 'Gate Hook', 'CSJ SNAP GATE HOOK'),
    ('Deck Hardware and Fittings', 'Guard rail', '21000687/2'),
    ('Deck Hardware and Fittings', 'Hatch Latch', 'SO M1 64 8'),
    ('Deck Hardware and Fittings', 'Helicoil Screw', 'INSRT R06'),
    ('Deck Hardware and Fittings', 'helm cup holder', 'RECSD CUP HLDR'),
    ('Deck Hardware and Fittings', 'Helm station lifeline padeye', 'PADEYE WD6605'),
    ('Deck Hardware and Fittings', 'Helm station padeye backing plate', '21000534'),
    ('Deck Hardware and Fittings', 'HTX 72mm single block', 'BLK LW29197201'),
    ('Deck Hardware and Fittings', 'Hull window Portlight', 'PTLT L393129804'),
    ('Deck Hardware and Fittings', 'inboard hull U-bolts( dinghy )', 'U-BLT12X155S'),
    ('Deck Hardware and Fittings', 'Inspection Hatch', 'HTCH ACI 195382'),
    ('Deck Hardware and Fittings', 'inspection port engine room', 'INSPRT AAA4WHT'),
    ('Deck Hardware and Fittings', 'Jammer single clutch', 'JMR SL XTS08141'),
    ('Deck Hardware and Fittings', 'lift platform folding chocks', 'HYDLFT CHCKS'),
    ('Deck Hardware and Fittings', 'Lifting Platform box', 'HTCH NR 196461'),
    ('Deck Hardware and Fittings', 'Lifting Platform Center HDPE Strip', 'JC-11309'),
    ('Deck Hardware and Fittings', 'Perspex deck hatch 10 (heads)', 'HTCH L399104942'),
    ('Deck Hardware and Fittings', 'Perspex deck hatch 44', 'HTCH L399444984'),
    ('Deck Hardware and Fittings', 'PLANCHA GAS GRILL', 'C1-7734'),
    ('Deck Hardware and Fittings', 'PLANCHA GAS GRILL SCREWS', 'STCP3.5X12S'),
    ('Deck Hardware and Fittings', 'Plastimo Offshore 75 Compass', 'CMPS PL63858'),
    ('Deck Hardware and Fittings', 'Proximinty Sensor ( interim, black small one )', 'OMRON TL-W5MC PROXIMITY'),
    ('Deck Hardware and Fittings', 'Proximinty Sensor ( Navy blue one )', 'XS8C1A1PBL2 PROXIMITY'),
    ('Deck Hardware and Fittings', 'Rod Holder Hose- nWhite sanitation hose 1 1/2"', 'HSSN TRID XHD40'),
    ('Deck Hardware and Fittings', 'Saddles 10mm', 'SDL 10 RF498'),
    ('Deck Hardware and Fittings', 'STANTION BASE +SCREW', '20303021'),
    ('Deck Hardware and Fittings', 'swim ladder', '21000793/2'),
    ('Deck Hardware and Fittings', 'swim ladder black catch', 'PPCLP PTD0250'),
    ('Deck Hardware and Fittings', 'swim ladder bottom bolt spacer', 'M8 HDPE SPCR BLK'),
    ('Deck Hardware and Fittings', 'swim ladder hinge teflon stoppers', 'JC-23927'),
    ('Deck Hardware and Fittings', 'swim ladder teak steps', 'S/LDDR STEP L45'),
    ('Deck Hardware and Fittings', 'swim ladder teflon base stoppers', 'JC-23928'),
    ('Deck Hardware and Fittings', 'transom rub rails', 'TRNSMRBRL B3'),
    ('Deck Hardware and Fittings', 'WINDLASS quick aleph handle ( stainless steel )', 'WND QKALXTHNDL'),
    ('Electrical', '100Amp circuit breaker AC panel', 'CB 7584BBSS'),
    ('Electrical', '110v shorepower socket', 'MR 303SSEL-B'),
    ('Electrical', '2-Plate induction hob', 'HOB KEB81325'),
    ('Electrical', '220v shorepower socket', 'MR 303SSEL-BX'),
    ('Electrical', '5 CABIN MID-HEADS EXTRACTOR FAN', 'EXTR FAN 12V DC'),
    ('Electrical', 'AC Meter Panel', 'SWPNL 3611796'),
    ('Electrical', 'AFT cabin ceiling rope light', 'LT NL B8 OCA'),
    ('Electrical', 'AFT COCKPIT DOWNLIGHT (SHORT)', 'LT QUJANEWRM15SHRT'),
    ('Electrical', 'AGM HOUSE BATTERY 210AH', 'BAT AGM 12V 210AH'),
    ('Electrical', 'Aircon Display', 'CR DSP SMRT'),
    ('Electrical', 'Aircon display bezel', 'CR DSP BZL'),
    ('Electrical', 'B8 Saloon rope light', 'LT NL B8 FH1'),
    ('Electrical', 'Backbone terminator', 'RA AO6031'),
    ('Electrical', 'BATTERY ERMINAL BOOT (NEGATIVE)', 'CBL CAP INSUL BLK'),
    ('Electrical', 'Battery Exide 12V 180AH', 'BAT EXD 12V180A'),
    ('Electrical', 'Battery Isolator switch', 'BAT ISOSW L45/1'),
    ('Electrical', 'Battery terminals', 'BTRY TRM'),
    ('Electrical', 'Blank plug / dust cover', 'RA A06032'),
    ('Electrical', 'BOSCH OVEN 110V', 'MCR OVN HMC54151 UC'),
    ('Electrical', 'CABIN AIRCON 10k BTU', 'CR TX10 410A'),
    ('Electrical', 'Cabin reading light', 'LT QUAUDWUSB1030 BC'),
    ('Electrical', 'Camera Coupler', 'RA 4115028'),
    ('Electrical', 'Control Circuit Module', 'RA E70317'),
    ('Electrical', 'Cordless Cell Charger', 'BTRCHG 14.515.02'),
    ('Electrical', 'Curtesy/Emergency Light', 'LT QUEYEW'),
    ('Electrical', 'Elec grill 110v', 'C1-7730'),
    ('Electrical', 'elec grill 220v', 'C1-7731'),
    ('Electrical', 'Electric Grill', 'GRL B70060US'),
    ('Electrical', 'ELECTRIC GRILL LID MAGNET', 'MGNT MMPSM'),
    ('Electrical', 'ELECTRIC GRILL PROXY SENSOR', 'MMPSA 240/3 PROX SWITCH'),
    ('Electrical', 'exhaust temp sensor', 'EXST TS VXHSM'),
    ('Electrical', 'FAN', 'FAN CAFBOR12/3W'),
    ('Electrical', 'FlybridgeStrip Light Long', 'LT NL B8FH2'),
    ('Electrical', 'Fusion Amp 2way', 'FU AP-DA214'),
    ('Electrical', 'Fusion exterior remote', 'FU MSNRX300'),
    ('Electrical', 'Fusion speaker 7,7" 240W', 'FU XS-F77CWB'),
    ('Electrical', 'Fusion Stereo', 'FU MS-RA770'),
    ('Electrical', 'FWD Cabin Lamp', 'LT QUSHARON15CL'),
    ('Electrical', 'Fwd Cockpit Door', 'CKPT DR B4F'),
    ('Electrical', 'Genset Battery', 'BAT AGM GPL2700'),
    ('Electrical', 'Helm Down light', 'LT QUEDWCDL'),
    ('Electrical', 'J Hook for Batteries', 'BAT HDJHK'),
    ('Electrical', 'M2 AC VOLT METER', 'MLTMTR BS1838 AC'),
    ('Electrical', 'M2 DC VOLTMETER', 'MLTMTR BS1830 DC'),
    ('Electrical', 'MFD card Reader for flybridge', 'RA A80440'),
    ('Electrical', 'NEW CABIN fan', 'FAN CAFBORII 12V WHT/2'),
    ('Electrical', 'new smoke detector', 'SMK ALRM SMl100RV 9V'),
    ('Electrical', 'Port/STB Nav light', 'NVLT H980520911'),
    ('Electrical', 'Quick LED Downlight', 'LT QUEDWCLUB02'),
    ('Electrical', 'rail end stoppers', 'END BRKT CLIPFIX'),
    ('Electrical', 'RAMARINE ITC-5 MULTI POD', 'RA E70010'),
    ('Electrical', 'Raymarine AR 200', 'RA E70537'),
    ('Electrical', 'Raymarine Camera', 'RA E70660'),
    ('Electrical', 'RAYMIC', 'RA A80289'),
    ('Electrical', 'Raymic Extension cable', 'RA A80292'),
    ('Electrical', 'Reading light', 'LT QUNIC'),
    ('Electrical', 'Saloon Ceiling Rope Light', 'LT NL B8 SC'),
    ('Electrical', 'Samsung Saloon fridge', 'RFRG RF49A5202SL'),
    ('Electrical', 'SeaTalk NG 5 Way connector + 1 blue terminator', 'RA A06064'),
    ('Electrical', 'shaver outlet 110v /220v white', 'SCKT SHVR 3 MOD WH'),
    ('Electrical', 'Shaver outlet 220v', 'ELEC B8-4201'),
    ('Electrical', 'Shower sump pump', 'PMP WHBP2082B'),
    ('Electrical', 'Sterling Charger', 'BTRCHG AB12130'),
    ('Electrical', 'Tank full indicator', 'SL TNKFLINDPNL'),
    ('Electrical', 'Terminator female', 'YNMR VRC TF'),
    ('Electrical', 'TERMINATOR MALE', 'YNMR VRC TM'),
    ('Electrical', 'USB C-SOCKET', 'CHRG SCKT OUTLET USB'),
    ('Electrical', 'VCS NMEA adaptor cable', 'YNMR VRC HNA'),
    ('Electrical', 'vertifrigo aftcockpit,galley fridge/freezer', 'RFRG DRW70AOCX2'),
    ('Electrical', 'VHF', 'RA E70517'),
    ('Electrical', 'VHF Antenna', 'VHF ANT 0354-2'),
    ('Electrical', 'VHF Cohex plugs', 'VHF MALE CNTR'),
    ('Electrical', 'Victron Charge Controller VE. Can', 'BTRCHC SCC MPPT150/70'),
    ('Electrical', 'Victron Charger MPPT', 'BTRCHC BSV MPPT100/30'),
    ('Electrical', 'WATERMAKER 50A BREAKER', 'CIRC BRKR SNGL PLE 50A/MCB'),
    ('Electrical', 'watermaker display controller', 'WMKR B61 100004'),
    ('Electrical', 'WATERMAKER SEA RECOVERY 12VDC/400GPD', 'WMKR SR A012C-112'),
    ('Electrical', 'WIND MASTHEAD UNIT WIRE 30M', 'AH50 WNDMHU'),
    ('Joinery and Interior', '3C Heads Inspection Panel', 'JC-08912'),
    ('Joinery and Interior', 'Aft cabin blind', 'BLND B8 CW'),
    ('Joinery and Interior', 'Anchor Chain teflon chaffe Plate', 'JC-23430'),
    ('Joinery and Interior', 'andr', 'HTCH ACI 195381'),
    ('Joinery and Interior', 'B8 Ceiling Poppers Male', 'FMT PCVM1'),
    ('Joinery and Interior', 'B8 S/S stair trim', '21000699'),
    ('Joinery and Interior', 'Blind Fwd Helm', 'BLND B8 FS'),
    ('Joinery and Interior', 'BLIND HEADS', 'BLND BS49/35W'),
    ('Joinery and Interior', 'Blind Transom Window', 'BLND B8 TW'),
    ('Joinery and Interior', 'BRACKET HINGE FOR ABOVE', 'SFT DN STY MNTNG PLT'),
    ('Joinery and Interior', 'Butt Hinge Cabin Door', 'HNGBT SS50X50/2'),
    ('Joinery and Interior', 'Butt hinges', 'HNGBT RPCB63X51'),
    ('Joinery and Interior', 'cabin door hinges', 'HNGNT SS50X50/2'),
    ('Joinery and Interior', 'Cabin door lock', 'LKRC 701508024'),
    ('Joinery and Interior', 'Cabin door mirror', 'MRR B4 CBNDR'),
    ('Joinery and Interior', 'Cabin Fwd Port Mirror', 'MRR B8 CBN FP'),
    ('Joinery and Interior', 'Cabin light switch backing plate', 'SUP FRM 2 MOD'),
    ('Joinery and Interior', 'Ceiling poppers F', 'FMT LPAF8A'),
    ('Joinery and Interior', 'Ceiling poppers M', 'FMT LPM8A'),
    ('Joinery and Interior', 'Coat hook', 'TWL HK Q312'),
    ('Joinery and Interior', 'Coffee table strap', 'STRP B5 CFFTBL'),
    ('Joinery and Interior', 'Consealed hinges VANITY DOOR', 'HNGC S304BC4619'),
    ('Joinery and Interior', 'CWD floor angle cover strip', 'CVR STRP CWDR'),
    ('Joinery and Interior', 'DB DOME COVER', 'VAC ELEC DB CVR'),
    ('Joinery and Interior', 'dishwasher catch', 'DR STP OSC60'),
    ('Joinery and Interior', 'Door catches M/F Black', 'CTCH SOCO C3805'),
    ('Joinery and Interior', 'Draw Runner Clip', 'DRWRSLD HE9257260'),
    ('Joinery and Interior', 'Dust bin (small)- heads', 'DSTBN HL WPWH5'),
    ('Joinery and Interior', 'Engine room ladder step', 'JC-06001'),
    ('Joinery and Interior', 'FLOOR STUDS', 'RVTS AS48127'),
    ('Joinery and Interior', 'Fly bridge TBL leg', '21000760'),
    ('Joinery and Interior', 'Flybridge Popper Female', 'FMT PCF1A'),
    ('Joinery and Interior', 'Formica Highland Ash', 'LMNT MAX 45185 RC4'),
    ('Joinery and Interior', 'fwd cockpit door blind', 'BLND B8 FCD/2'),
    ('Joinery and Interior', 'galley locker conceled hinge', 'HNGC S304BC469'),
    ('Joinery and Interior', 'GALLEY LPG METAL LABEL', 'LPG PLT GLLY'),
    ('Joinery and Interior', 'Hanging Door Mirror', 'MRR B8 HLD'),
    ('Joinery and Interior', 'Hanging rail end stopper/cup', 'END SOCKET'),
    ('Joinery and Interior', 'Heads door guide - bottom B4', '21000153'),
    ('Joinery and Interior', 'HEADS DOOR SLIDING LABEL ( WHITE - OUTSIDE )', 'LBL SDLO'),
    ('Joinery and Interior', 'Heads sliding door wheels', 'DR H100 TF/SS'),
    ('Joinery and Interior', 'Heads Vanity Mirror', 'MRR B8 HDSVL'),
    ('Joinery and Interior', 'Helm Panel', 'JA-30270'),
    ('Joinery and Interior', 'Light switch covers', 'CVR PLT 3 MOD GRPH'),
    ('Joinery and Interior', 'LPG TANK METAL LABEL', 'LPG PLT TNK'),
    ('Joinery and Interior', 'Magnet cabin door - piel', 'CTCH 0107361P'),
    ('Joinery and Interior', 'Magnet HEADS door - UPSTAND', 'CTCH 0207671N'),
    ('Joinery and Interior', 'Midget vent', 'MDGT VNTKH 81360'),
    ('Joinery and Interior', 'NAV DESK HINGE', 'SFT DN STY LH'),
    ('Joinery and Interior', 'OV cain inboard desk mirror ( 300mmX330mm)', 'MRR B4 DSK'),
    ('Joinery and Interior', 'OV Heads Blind', 'BLND BS1025/490W'),
    ('Joinery and Interior', 'OV study desk mirror', 'MRR B6 HDSA/2'),
    ('Joinery and Interior', 'Owners Heads door latch', 'LTCH MF0131024'),
    ('Joinery and Interior', 'Port aft heads FWD vanity mirror (B)', 'MRR C1 AHPBVL'),
    ('Joinery and Interior', 'Port aft heads top vanity mirror (A)', 'MRR C1 AHPAVL'),
    ('Joinery and Interior', 'PORT AFTHEADS SHOWER RAIL PANEL', 'JC-26012'),
    ('Joinery and Interior', 'Port fwd cabin ac locker inspection', 'JC-25573'),
    ('Joinery and Interior', 'Port fwd cabin bunk lid', 'JC-27419'),
    ('Joinery and Interior', 'Port fwd cabin floor lid', 'JC-26975'),
    ('Joinery and Interior', 'port fwd cabin floor lid- genset ball valve floor', 'JC-36166'),
    ('Joinery and Interior', 'Port passage big floor lid( fwd one)', 'JC-24813'),
    ('Joinery and Interior', 'Saloon battery floor lid', 'JC-32022'),
    ('Joinery and Interior', 'Saloon Battery lid', 'JC-21036'),
    ('Joinery and Interior', 'Saloon Bin', 'DSTBN AD 31074BK'),
    ('Joinery and Interior', 'Saloon dust bin', 'DSTBN AD 91074BK'),
    ('Joinery and Interior', 'Saloon front door BLND', 'BLND B8 FCD'),
    ('Joinery and Interior', 'Saloon light switch backing plate', 'SUP FRM 3 MOD'),
    ('Joinery and Interior', 'Saloon TV Lift', 'TV LFT TS1000A'),
    ('Joinery and Interior', 'SCREEN SCREW SIZE 10(HEADS)', 'SSRLX10W'),
    ('Joinery and Interior', 'SHOE LOCKER/VANITY', 'SFT DN STY RH'),
    ('Joinery and Interior', 'Size 44 Skyscreen', 'SSSRSLX44BSLR'),
    ('Joinery and Interior', 'Size 60 sky screen', 'SSSRSLX60BSLR'),
    ('Joinery and Interior', 'Sliding door rail/track', 'DR SA280A/1800'),
    ('Joinery and Interior', 'Soft Close Hinge', 'HNGDHGJHM1634BL'),
    ('Joinery and Interior', 'Soft Close Hinge', 'HNGSC JHM112BL'),
    ('Joinery and Interior', 'Stb aft cabin floor lid', 'JC-26006'),
    ('Joinery and Interior', 'STB AFT CABIN high voltage panel', 'JC 08753'),
    ('Joinery and Interior', 'STB AFT CABIN high voltage panel', 'JC 08754'),
    ('Joinery and Interior', 'STB AFT HEADS -OV HEADS', 'MRR C1 AHSBVL'),
    ('Joinery and Interior', 'stb aft heads waste tank inspection panel (4 cabin boat)', 'JC-25981'),
    ('Joinery and Interior', 'STB Cabin Mirror', 'MRR B8 CBN FS'),
    ('Joinery and Interior', 'Stb fwd cabin depth transducer floor lid', 'JC-36136'),
    ('Joinery and Interior', 'STB fwd heads mirror', 'MRR C1 FHSVL'),
    ('Joinery and Interior', 'STB Galley Locker Door', 'JC-20635'),
    ('Joinery and Interior', 'STRIKER PLATE-DOOR', '21000368'),
    ('Joinery and Interior', 'Teak Swim ladder Step', 'S/LDDR STPS L45'),
    ('Joinery and Interior', 'Toggle Plate + Screw', '21000508'),
    ('Joinery and Interior', 'Toilet roll holder', 'TLT RL HLDRR282'),
    ('Joinery and Interior', 'TV bracket strop', 'STRP B8 TVBRKT'),
    ('Joinery and Interior', 'Vanity locker hinges', 'HNGC B79T9550'),
    ('Loose items/Skipper''s pack', '72mm HTX Single Block with Becket (On Deck)', 'BLK LW 29197204'),
    ('Loose items/Skipper''s pack', '72mm HTX Single Block with Fiddle (On Boom)', 'BLK LW 29197231'),
    ('Loose items/Skipper''s pack', '8MM X 2.8M YACHTMASTER WHITE', 'RP LPTCKL BLKFST'),
    ('Loose items/Skipper''s pack', '8MM X 20M YACHTMASTER WHITE', 'RP LPTCKL HST'),
    ('Loose items/Skipper''s pack', 'Anchor Plastimo Britany 16kg', 'ANCHR PL16463'),
    ('Loose items/Skipper''s pack', 'Anchor warp 61mx20mm', 'ANCWRP 61MX20MM'),
    ('Loose items/Skipper''s pack', 'Battery charger Metabo', 'BTRCHG 135 AC S145'),
    ('Loose items/Skipper''s pack', 'Battery pack Metabo', 'BAT PCK 18V 10A'),
    ('Loose items/Skipper''s pack', 'Big shackle', 'SHCKL GB-3/4'),
    ('Loose items/Skipper''s pack', 'Black mooring line 10m', 'MRNGLNB 10MX16MM'),
    ('Loose items/Skipper''s pack', 'BLOCK 40MM TRIPLE + BECKET CAM CLEAT & SWIVL HEAD', 'BLK LW29901430BK'),
    ('Loose items/Skipper''s pack', 'BLOCK 40MM TRIPLE WITH SWIVEL HEAD', 'BLK LW29901423BK'),
    ('Loose items/Skipper''s pack', 'Boat hook, 6ft', 'BTHK6 RC'),
    ('Loose items/Skipper''s pack', 'Bucket Lid 2.5L White', 'BCKLD2'),
    ('Loose items/Skipper''s pack', 'Carbine hook 10m', 'CRBNHK 10MM'),
    ('Loose items/Skipper''s pack', 'Catalyst Butanox M50', 'CTLST BTNXM50'),
    ('Loose items/Skipper''s pack', 'Chain calibraded 8mx10mm Galvanised', 'CHN CAL08MX10MM'),
    ('Loose items/Skipper''s pack', 'Cordless Metabo angle grinder', 'GRINDER CRDLS BL 15-15'),
    ('Loose items/Skipper''s pack', 'Crew Strop', 'RP L44 BMO/HLFX'),
    ('Loose items/Skipper''s pack', 'Cutting disk diamond blade', 'CTGDSCDRB 125MM'),
    ('Loose items/Skipper''s pack', 'Deck brush (R&C supply)', 'DCKBRSH RC'),
    ('Loose items/Skipper''s pack', 'Dishrack', 'DSHRCK AD GRNT'),
    ('Loose items/Skipper''s pack', 'Dividers brass 17cm Plastimo', 'DVDR 10558'),
    ('Loose items/Skipper''s pack', 'Dome Tag', 'DCL RC LOGO'),
    ('Loose items/Skipper''s pack', 'Electric Spares', 'ELECSPRS L47'),
    ('Loose items/Skipper''s pack', 'Fender Plastimo', 'FNDR 39621'),
    ('Loose items/Skipper''s pack', 'Fire blanket 900x900mm Chubb', 'FR BLNKT'),
    ('Loose items/Skipper''s pack', 'Fire Hose', 'FRXT HS EXT ASSY'),
    ('Loose items/Skipper''s pack', 'First aid kit Plastimo Offshore', 'FRSTAID 10320'),
    ('Loose items/Skipper''s pack', 'Flag Q Plastimo #17033', 'FLGQ'),
    ('Loose items/Skipper''s pack', 'Flag USA 37cm×57cm #1/82441', 'FLGUSA'),
    ('Loose items/Skipper''s pack', 'Flare hand-held red (R&C SUPP)', 'FLR HR RC'),
    ('Loose items/Skipper''s pack', 'Flowcoat White K408 PA', 'FLWCT WHT 408'),
    ('Loose items/Skipper''s pack', 'Foghorn 30cm Plastimo #16183', 'FGHORN 16183'),
    ('Loose items/Skipper''s pack', 'Foot Loops', 'FTMNLP 30'),
    ('Loose items/Skipper''s pack', 'Funnel Flexible', 'FNNL'),
    ('Loose items/Skipper''s pack', 'Furler', 'FRLR NEX6.5'),
    ('Loose items/Skipper''s pack', 'Galv Shackle Small', 'SHCKL GB11 PB'),
    ('Loose items/Skipper''s pack', 'Gas bottle strap', 'GS BTTL STRP'),
    ('Loose items/Skipper''s pack', 'Gelcoat Ultragel White', 'GCN22P10075PAE'),
    ('Loose items/Skipper''s pack', 'Halyard Tail Bags', 'HLYD TLBG L44/L48'),
    ('Loose items/Skipper''s pack', 'Hardcase water and dust proof box', 'HRDCSE BOX WD PROOF SML'),
    ('Loose items/Skipper''s pack', 'Label inversion emergency exit', 'LBL INV EMG EXIT'),
    ('Loose items/Skipper''s pack', 'Lifering Plastimo Yellow', 'LFRG 16102'),
    ('Loose items/Skipper''s pack', 'Lifting Labels', 'LBLS LFT AREA GRY'),
    ('Loose items/Skipper''s pack', 'Lifting platform straps', 'STRP B5 LFTP'),
    ('Loose items/Skipper''s pack', 'Mooring line 10m x 18mm (white)', 'MRNGLN 10Mx18MM'),
    ('Loose items/Skipper''s pack', 'Mooring line 15m x 18mm (white)', 'MRNGLN 15Mx18MM'),
    ('Loose items/Skipper''s pack', 'Mooring line 15m x 18mm (white)', 'MRNGLNB 15MX16MM'),
    ('Loose items/Skipper''s pack', 'No Step Labels', 'DCL NSTP B3'),
    ('Loose items/Skipper''s pack', 'Padeye oblong base 90mm x 31mm', 'PADEYE 22-69212'),
    ('Loose items/Skipper''s pack', 'PARRALLEL RULER', 'PRLLL RL'),
    ('Loose items/Skipper''s pack', 'Plastic Bucket 2.5L Koogan T/E', 'BCKT2'),
    ('Loose items/Skipper''s pack', 'RED FENDER LINE', 'RP-FNDR'),
    ('Loose items/Skipper''s pack', 'Red web strap', 'STRP 3M X 25 RD'),
    ('Loose items/Skipper''s pack', 'Reefing safety sign', 'RFNG SFTY SGN'),
    ('Loose items/Skipper''s pack', 'ROPE BOWSPRIT SUPPORT', 'RP BWSPRT'),
    ('Loose items/Skipper''s pack', 'Rope, Flag halyard 5m × 3mm', 'RP-FLGHLYD'),
    ('Loose items/Skipper''s pack', 'Rope, painter 11m × 12mm', 'RP-PNTR'),
    ('Loose items/Skipper''s pack', 'Ships Bell 6" Chromed Brass', 'SHPS BLL 6'),
    ('Loose items/Skipper''s pack', 'VELCRO STRAP ESCAPE HATCH C2', 'STRP C2 ESC HTC'),
    ('Loose items/Skipper''s pack', 'Winch handle 10" Alum lock-in', 'WN HNDL 10AL HA'),
    ('Loose items/Skipper''s pack', 'Winch handle 10" Alum plain', 'WN HNDL29141110'),
    ('Loose items/Skipper''s pack', 'Windlass Quick Antares Handle', 'WN QKATHNDL'),
    ('Mechanical', '10/12Kw Genset Casing', 'NL SNDSHLD 0679150/2'),
    ('Mechanical', '9kw genset casing', 'NL SNDSHLD 06-78650'),
    ('Mechanical', 'battery box powercat', 'BAT BX 55372'),
    ('Mechanical', 'battery box sail boat', 'BAT BX 55362'),
    ('Mechanical', 'BULKHEAD STEERER', 'STRNG L89101475'),
    ('Mechanical', 'Engine Room Blower', 'BLWR JB35770-0092'),
    ('Mechanical', 'engine water strainer, Vetus', 'WTRSTR VTS3338'),
    ('Mechanical', 'FIRE SUPPRESSION CABLE KIT', 'CR DSP CBL25 TX'),
    ('Mechanical', 'Fuel Tank', 'TNK FL B8'),
    ('Mechanical', 'Fuel Tank Level Sensor', 'HPMS0061'),
    ('Mechanical', 'Generator Start Panel', 'NL 2295611'),
    ('Mechanical', 'Hydraulic oil Bottles', 'BTTL SPRY 1L'),
    ('Mechanical', 'Hydraulic Power Pack', 'LS 2203841'),
    ('Mechanical', 'Jabsco Fuel Transfer Pump', 'PMP JBSC 23870'),
    ('Mechanical', 'Racor Fuel Filter', 'FUEL FLTR 500MA10'),
    ('Mechanical', 'Sea Recovery Watermaker', 'WMKR SR A012C-111'),
    ('Mechanical', 'Steering wheel-stainless', 'STRNG L89700289'),
    ('Miscellaneous', '110V Shorepower label set', 'LBLS RC C1-4100'),
    ('Miscellaneous', '110V Shorepower lead', 'SHPWR 199119'),
    ('Miscellaneous', '220v Shorepower head plug', 'SHPWR PL 32A230'),
    ('Miscellaneous', '220V Shorepower lead', 'SHPWR 15M32AXP'),
    ('Miscellaneous', '60mm block with becket', 'LW29196004'),
    ('Miscellaneous', '60mm block with fiddle', 'LW29196031'),
    ('Miscellaneous', 'AIRCON Labels', 'LBLS RC C1-5255'),
    ('Miscellaneous', 'B3 LabEL Pack', 'LBLS RC B3'),
    ('Miscellaneous', 'Black fender', 'FNDR A0453BKSD'),
    ('Miscellaneous', 'Black fender rope', 'RP-FNDRB'),
    ('Miscellaneous', 'Chiller QR codes', 'DCL QRC FACI'),
    ('Miscellaneous', 'Composite wheel black', 'STRNG L89700943'),
    ('Miscellaneous', 'Cutlery Tray', 'CTLRY TRAY GRNT'),
    ('Miscellaneous', 'Depth LBLS', 'LBLS RC B1-3305'),
    ('Miscellaneous', 'Depth LBLS', 'LBLS RC B2-3304'),
    ('Miscellaneous', 'DISH RACK', 'DSHRCK AD GRANT'),
    ('Miscellaneous', 'Electrical label set', 'LBLS RC C1 ELEC'),
    ('Miscellaneous', 'Fenders ( Polyform ) moorings', 'FNDR F3 WHT'),
    ('Miscellaneous', 'Fire Suppression Labels', 'LBLS RCB4-2100'),
    ('Miscellaneous', 'Flex mould', 'FLXMLD GFO 103'),
    ('Miscellaneous', 'Flex mould', 'GFD103'),
    ('Miscellaneous', 'GENSET Label set', 'LBLS RC B9-5200'),
    ('Miscellaneous', 'Inverter/Charger Labels', 'LBLS RC B2-4300'),
    ('Miscellaneous', 'JAMMER labels', 'JMR L25005153'),
    ('Miscellaneous', 'Pool Noodle', 'AEROTB4072W'),
    ('Miscellaneous', 'Reefing saftey sign', 'RFNG SFTY SGNB4'),
    ('Miscellaneous', 'Salt/fresh toilet Labels', 'LBLS RC DUAL SWITCH'),
    ('Miscellaneous', 'skippers pack chair', 'CHR GRY 61112'),
    ('Miscellaneous', 'Sliding/Heads door Labels - Open/Close', 'LBL SDLI/O'),
    ('Miscellaneous', 'Teak Cleaner', 'TKDCK MNTNCKT'),
    ('Miscellaneous', 'Transom Shower bag', 'STRNSHWRBG B6'),
    ('Miscellaneous', 'Water maker Labels', 'LBLS RC B2-6500'),
    ('Miscellaneous', 'Watermaker label set', 'LBLS RC C1-6520'),
    ('Plumbing', '110V water heater', 'HWC B32506SL 110V'),
    ('Plumbing', '15mm One way valve - Grey', 'SF 15DCV'),
    ('Plumbing', '15MM pipe stopper', 'SF PSE4615W'),
    ('Plumbing', '220V water heater', 'HWC B32505S 220V'),
    ('Plumbing', '500ml Bottle', 'BTTL500'),
    ('Plumbing', '5inch duckting joiner round', 'MS HR5'),
    ('Plumbing', 'Aircon 110v OR 220V', 'CR DTG16-410S 110V OR CR DTGX16-410S 220V'),
    ('Plumbing', 'Aircon 25mm adapter( straight piece)', 'ADPTR 25HS3/4BS'),
    ('Plumbing', 'Aircon Ducting', 'AIRDCT MKE5'),
    ('Plumbing', 'Aircon pump male insert adapter( straight piece)', 'INSMLADPT25'),
    ('Plumbing', 'Aircon Seawater Pump 110v OR 220V', 'CR PML500 OR CR PML500C'),
    ('Plumbing', 'Aircon Transition Box', 'MS TB105'),
    ('Plumbing', 'Anti Syphon Small', 'ANTSYPH V 13-32'),
    ('Plumbing', 'Anti syphon valve', 'ANTSYPH ASD38V'),
    ('Plumbing', 'Anti-Syphon Loop ( toilet )', 'ANTSPHN LP 19'),
    ('Plumbing', 'B8 Saloon mixer', 'FCT BRK MDY1401'),
    ('Plumbing', 'B8 waste tank', 'WSTTK B4/22'),
    ('Plumbing', 'Ball Valve', 'VLV PVC CHE0635'),
    ('Plumbing', 'Bildge pump 2000', 'PMP RL 2000'),
    ('Plumbing', 'Braded hose shower long', 'CNTR BSS151000X'),
    ('Plumbing', 'Braided Hose', 'HSPVC20'),
    ('Plumbing', 'Brass shower mixer elbows', 'ELB BS 2202-8-8'),
    ('Plumbing', 'C-Clip Blue', 'SF CM1815B'),
    ('Plumbing', 'C-Clip Red', 'SF CM1815R'),
    ('Plumbing', 'Cabin Aircon Vent', 'MS VMLP105M7F'),
    ('Plumbing', 'DECK WASH LABEL SET', 'LBLS RC B8-6800'),
    ('Plumbing', 'engine room bilge pump', '1100GPH/12V'),
    ('Plumbing', 'Female Coupler Speed Fitting', 'SF PSE3201W'),
    ('Plumbing', 'Float switch', 'PMP RL FLSW37'),
    ('Plumbing', 'Fresh water pump B3', 'PMP JBSC Q401J'),
    ('Plumbing', 'Gas Hob', 'HOB MIKM2010'),
    ('Plumbing', 'Gas Regulator', 'GS REG TR1SGP'),
    ('Plumbing', 'heads basin mixer', 'FCT BA MJA1000'),
    ('Plumbing', 'Heads Drain stopper', 'DRN BRK PF2535'),
    ('Plumbing', 'Hull ball Valve', 'VLV BC6 F932156'),
    ('Plumbing', 'Insert coupling-Dish washer', 'INSCP 40'),
    ('Plumbing', 'Main bilge pump', 'RULE 2000 GPH/12V'),
    ('Plumbing', 'Male Screw Speed Fitting', 'SF NC2556 ST'),
    ('Plumbing', 'metal waterheater elbow fitting', 'ELB NPTFSW-0810'),
    ('Plumbing', 'Non-Return Valve', 'VLV N/R WHL2538'),
    ('Plumbing', 'Perfix clips F', 'PE 2011'),
    ('Plumbing', 'Perfix clips F', 'PE 2011-100'),
    ('Plumbing', 'Pipe clamp covers Big', 'HSCLMP EC12'),
    ('Plumbing', 'Pipe clamp covers Small', 'HSCLMP EC516'),
    ('Plumbing', 'Purifier tap', 'WTRPRFR SGLIVX2KF WF'),
    ('Plumbing', 'Reducer skin fitting attachment 3/4"', 'RED MGE3/4X1'),
    ('Plumbing', 'Saloon aircon T-piece foam insulation', 'INSUL HY 754'),
    ('Plumbing', 'Saloon Fridge/Frezer- 2 door', 'RFRG DW2102DTOCX2'),
    ('Plumbing', 'Shower Head and rail', 'SHWR BA SY180100'),
    ('Plumbing', 'shower pump (Black/yellow)', 'PMP WHBP2082B/2'),
    ('Plumbing', 'Shower sump', 'SHWR GLLSG1984B'),
    ('Plumbing', 'SHUTOFF VALVE 15MM', 'SF 15ESOT'),
    ('Plumbing', 'Speed Fit Elbow', 'SF PEM0315W'),
    ('Plumbing', 'Spout for bottle', 'BTTLSPT'),
    ('Plumbing', 'stb fwd heads waste tank', 'WSTTK B4/13'),
    ('Plumbing', 'toilet', 'TLT SYST SN31C'),
    ('Plumbing', 'toilet salt/fresh switch cap', 'SWC ACT VVPZY00-000'),
    ('Plumbing', 'Toilet switch salt/fresh water bezel', 'SWC BZL VMS-02'),
    ('Plumbing', 'Transom Shower hot/cold', 'SHWR TRM OSCHC25720'),
    ('Plumbing', 'Twist Bung', 'BNGBG122C'),
    ('Plumbing', 'Washdown Quick connct Aquor 2 parts', 'WSHDWN QCDW3'),
    ('Plumbing', 'Washing machine adaptor', 'SF 15APT'),
    ('Plumbing', 'Water heater Elbow', 'ELB NPTSW-0810'),
    ('Plumbing', 'water pump guard', 'PMP GRD 12S'),
    ('Plumbing', 'Watermaker Cable (orange )', 'WMKR SR A012C KIT'),
    ('Plumbing', 'Watermaker Sea Strainer', 'WMKR SS A012C'),
    ('Plumbing', 'Wetbar tap', 'FCT BRK MR4100L'),
    ('Safety', 'Black full plastic fire extinguisher bracket', 'FRXTNGSHR'),
    ('Safety', 'CO2 Alarm', 'CO ALRM FX4'),
    ('Safety', 'emergency swim ladder', 'LDDR SFTY OSC4952500 MK2'),
    ('Safety', 'Fire extinguisher bracket-RED', 'FRXTNGSHR 1.0EVSFB'),
    ('Safety', 'Fire retard Tape', 'SD HTA'),
    ('Safety', 'Fire Suppression display', 'FRXT FXES300001'),
    ('Safety', 'Fire suppression tank+bracket', 'FRXT FXMA0450NVC'),
    ('Safety', 'LPG Control Unit', 'GS DTCT KT2 LPG'),
    ('Safety', 'Smoke Alarm', 'SMK ALRM SS775')
)
insert into public.stock_items (category_id, description, stock_code, search_terms)
select category.id, incoming.description, incoming.stock_code, array[incoming.description]
from incoming
join public.stock_categories category on category.name = incoming.category_name
on conflict do nothing;

-- Word-document matches take precedence for the combined loose-items category.
update public.stock_items
set category_id = (select id from public.stock_categories where name = 'Loose items/Skipper''s pack')
where regexp_replace(upper(stock_code), '[^A-Z0-9]', '', 'g') in (
  'BLKLW29197204',
  'BLKLW29197231',
  'RPLPTCKLBLKFST',
  'RPLPTCKLHST',
  'ANCHRPL16463',
  'ANCWRP61MX20MM',
  'BTRCHG135ACS145',
  'BATPCK18V10A',
  'SHCKLGB34',
  'MRNGLNB10MX16MM',
  'BLKLW29901430BK',
  'BLKLW29901423BK',
  'BTHK6RC',
  'BCKLD2',
  'CRBNHK10MM',
  'CTLSTBTNXM50',
  'CHNCAL08MX10MM',
  'GRINDERCRDLSBL1515',
  'RPL44BMOHLFX',
  'CTGDSCDRB125MM',
  'DCKBRSHRC',
  'DSHRCKADGRNT',
  'DVDR10558',
  'DCLRCLOGO',
  'ELECSPRSL47',
  'FNDR39621',
  'FRBLNKT',
  'FRXTHSEXTASSY',
  'FRSTAID10320',
  'FLGQ',
  'FLGUSA',
  'FLRHRRC',
  'FLWCTWHT408',
  'FGHORN16183',
  'FTMNLP30',
  'FNNL',
  'FRLRNEX65',
  'SHCKLGB11PB',
  'GSBTTLSTRP',
  'GCN22P10075PAE',
  'HLYDTLBGL44L48',
  'HRDCSEBOXWDPROOFSML',
  'LBLINVEMGEXIT',
  'LFRG16102',
  'LBLSLFTAREAGRY',
  'STRPB5LFTP',
  'MRNGLN10MX18MM',
  'MRNGLN15MX18MM',
  'MRNGLNB15MX16MM',
  'DCLNSTPB3',
  'PADEYE2269212',
  'PRLLLRL',
  'BCKT2',
  'RPFNDR',
  'STRP3MX25RD',
  'RFNGSFTYSGN',
  'RPBWSPRT',
  'RPFLGHLYD',
  'RPPNTR',
  'SHPSBLL6',
  'STRPC2ESCHTC',
  'WNHNDL10ALHA',
  'WNHNDL29141110',
  'WNQKATHNDL'
);

commit;

-- Verification: these should return 442 total rows and zero duplicate groups
-- for this import when the stock_items table was empty before running it.
select count(*) as stock_item_count from public.stock_items;
select regexp_replace(upper(stock_code), '[^A-Z0-9]', '', 'g') as normalized_code, count(*)
from public.stock_items
group by normalized_code
having count(*) > 1;
